#ifndef GENERATED_ASN1SCC_a_H
#define GENERATED_ASN1SCC_a_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"

#ifdef  __cplusplus
extern "C" {
#endif


typedef struct {
    
    byte arr[3];
} OOO;

flag OOO_Equal(const OOO* pVal1, const OOO* pVal2);

void OOO_Initialize(OOO* pVal);

#define ERR_UPER_ENCODE_OOO		1  /**/
#define OOO_REQUIRED_BYTES_FOR_ENCODING       3 
#define OOO_REQUIRED_BITS_FOR_ENCODING        20

flag OOO_Encode(const OOO* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_OOO		2  /**/
flag OOO_Decode(OOO* pVal, BitStream* pBitStrm, int* pErrCode);

 

/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */

 


#ifdef  __cplusplus
}

#endif

#endif
