#ifndef GENERATED_ASN1SCC_a_auto_tcs_h
#define GENERATED_ASN1SCC_a_auto_tcs_h
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "a.h"

#ifdef  __cplusplus
extern "C" {
#endif


flag OOO_enc_dec(const OOO* pVal, int* pErrCode);



#ifdef  __cplusplus
}
#endif

#endif
