
#ifndef GENERATED_ASN1SCC_test_case_001_H
#define GENERATED_ASN1SCC_test_case_001_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "testsuite.h"
#include "a_auto_tcs.h"

#ifdef  __cplusplus
extern "C" {
#endif
void test_case_UPER_000001(const TestOutput* output, int *totalErrors);

#ifdef  __cplusplus
}

#endif

#endif
