/*
Code automatically generated by asn1scc tool
*/
package asn1src

import asn1scala._
import stainless.lang._
import stainless.annotation._

/*-- Message --------------------------------------------*/
type Message_anInt = UInt // header_scala:83

type Message_tenByteString = Array[Byte]
case class Message (
    var anInt: Message_anInt,
    var tenByteString: Message_tenByteString,
    var aBool: Boolean
)

@inline @cCode.inline val ERR_MESSAGE_ANINT: Int = 1  /*(0..267) isvalid_scala:68 */

@inline @cCode.inline val ERR_MESSAGE_TENBYTESTRING: Int = 6  /*(SIZE(10)) isvalid_scala:68 */

@inline @cCode.inline val ERR_MESSAGE: Int = 16  /* isvalid_scala:68 */
@inline @cCode.inline val ERR_MESSAGE_ABOOL: Int = 11  /* isvalid_scala:68 */

 
 
 

@inline @cCode.inline val ERR_UPER_ENCODE_MESSAGE: Int = 17  /**/
@inline @cCode.inline val ERR_UPER_ENCODE_MESSAGE_ANINT: Int = 2  /**/
@inline @cCode.inline val ERR_UPER_ENCODE_MESSAGE_TENBYTESTRING: Int = 7  /**/
@inline @cCode.inline val ERR_UPER_ENCODE_MESSAGE_ABOOL: Int = 12  /**/
@inline @cCode.inline val Message_REQUIRED_BYTES_FOR_ENCODING: Int = 12 
@inline @cCode.inline val Message_REQUIRED_BITS_FOR_ENCODING: Int = 90

 

 