from commons import glob_files_recursive, get_files_with_suffix, list_files
from glob import glob

import os

import AsnBuilder

Import('env')
Import('PROXY')
Import('TEST_FILE')

def _get_bin_name(language):
    return os.path.basename(os.path.dirname(PROXY[0].path)) + "_{}_bin".format(language)

def _get_report_name():
    return os.path.basename(os.path.dirname(PROXY[0].path)) + "_report"

asn_files = env.Asn(AsnBuilder.get_output('.', TEST_FILE),
            [env['ASN_BIN']] + list_files(
                os.path.join(env['SCRIPT_DIR'], env['TEST_CASE'])))
asn_objects = env.Object(get_files_with_suffix(asn_files, '.c'))

variable_env = env.Clone()
variable_env.Append(CPPPATH='.')
variable_env.Append(CPPPATH=[os.path.basename(os.path.dirname(PROXY[0].path))])

obj = variable_env.Object([source for source in Glob(os.path.join('.', '*.c')) 
                  if os.path.basename(source.path) != 'ada_helpers.c'])

c_bin = variable_env.Program([_get_bin_name('c')], 
     obj + asn_objects + get_files_with_suffix(PROXY, '.c'))

ada_bin = env.Ada([_get_bin_name('ada')], get_files_with_suffix(PROXY, '.adb')[0:1] + env.Object('ada_helpers.c'))

env.Report([_get_report_name()], [c_bin, ada_bin])
