#
# Copy the current folder into the container and build asn1scc.
#
#################################################################################################
#################################################################################################

FROM  mcr.microsoft.com/dotnet/sdk:7.0 AS build

RUN apt update
RUN apt install -y python3 python3-distutils \
    gnat gcc g++ make openjdk-11-jre nuget libgit2-dev libssl-dev gprbuild ; apt clean


