-- Code automatically generated by asn1scc tool
with adaasn1rtl;
with uper_asn1_rtl;
with system;
use adaasn1rtl;
WITH D;

use type adaasn1rtl.OctetBuffer;
use type adaasn1rtl.BitArray;
use type adaasn1rtl.Asn1UInt;
use type adaasn1rtl.Asn1Int;
use type adaasn1rtl.BIT;
use D;
--# inherit ;


PACKAGE postencoding with SPARK_Mode
IS

procedure my_encoding_patcher(val:in T_Packet; bitStreamPositions_start1 : adaasn1rtl.BitStreamPtr; bitStreamPositions_1:T_Packet_extension_function_positions; bs : in out adaasn1rtl.Bitstream);

FUNCTION crc_validator(val:in T_Packet; bitStreamPositions_start1 : adaasn1rtl.BitStreamPtr; bitStreamPositions_1:T_Packet_extension_function_positions; bs : in out adaasn1rtl.Bitstream) return adaasn1rtl.ASN1_RESULT;


END postencoding;
