#ifndef GENERATED_ASN1SCC_a_auto_tcs_h
#define GENERATED_ASN1SCC_a_auto_tcs_h
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "a.h"

#ifdef  __cplusplus
extern "C" {
#endif


flag PacketHeader_ACN_enc_dec(const PacketHeader* pVal, int* pErrCode, const char* filename);

flag PacketBody_ACN_enc_dec(const PacketBody* pVal, int* pErrCode, const char* filename);

flag Packet_ACN_enc_dec(const Packet* pVal, int* pErrCode, const char* filename);



#ifdef  __cplusplus
}
#endif

#endif
