
#ifndef GENERATED_ASN1SCC_test_case_001_H
#define GENERATED_ASN1SCC_test_case_001_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "testsuite.h"
#include "a_auto_tcs.h"

#ifdef  __cplusplus
extern "C" {
#endif
void test_case_ACN_000001(const TestOutput* output, int *totalErrors);

void test_case_ACN_000002(const TestOutput* output, int *totalErrors);

void test_case_ACN_000003(const TestOutput* output, int *totalErrors);

void test_case_ACN_000004(const TestOutput* output, int *totalErrors);

void test_case_ACN_000005(const TestOutput* output, int *totalErrors);

void test_case_ACN_000006(const TestOutput* output, int *totalErrors);

void test_case_ACN_000007(const TestOutput* output, int *totalErrors);

void test_case_ACN_000008(const TestOutput* output, int *totalErrors);

void test_case_ACN_000009(const TestOutput* output, int *totalErrors);

void test_case_ACN_000010(const TestOutput* output, int *totalErrors);

void test_case_ACN_000011(const TestOutput* output, int *totalErrors);

void test_case_ACN_000012(const TestOutput* output, int *totalErrors);

void test_case_ACN_000013(const TestOutput* output, int *totalErrors);

void test_case_ACN_000014(const TestOutput* output, int *totalErrors);

void test_case_ACN_000015(const TestOutput* output, int *totalErrors);

void test_case_ACN_000016(const TestOutput* output, int *totalErrors);

#ifdef  __cplusplus
}

#endif

#endif
