pragma Style_Checks (Off);
--  Code automatically generated by asn1scc tool
pragma Warnings (Off, "no entities of ""Interfaces"" are referenced");
with Interfaces;
pragma Warnings (On, "no entities of ""Interfaces"" are referenced");

pragma Warnings (Off, "use clause for package ""Interfaces"" has no effect");
use Interfaces;
pragma Warnings (On, "use clause for package ""Interfaces"" has no effect");

with adaasn1rtl;


pragma Warnings (Off, "unit ""System"" is not referenced");
with System;
pragma Warnings (On, "unit ""System"" is not referenced");

pragma Warnings (Off, "use clause for package ""adaasn1rtl"" has no effect");
use adaasn1rtl;
pragma Warnings (On, "use clause for package ""adaasn1rtl"" has no effect");

pragma Warnings (Off, "use clause for type");
pragma Warnings (Off, "is already use-visible through package use clause at line");
use type adaasn1rtl.OctetBuffer;
use type adaasn1rtl.BitArray;
use type adaasn1rtl.Asn1UInt;
use type adaasn1rtl.Asn1Int;
use type adaasn1rtl.BIT;
pragma Warnings (On, "use clause for type");
pragma Warnings (On, "is already use-visible through package use clause at line");



package MY_MODULE with SPARK_Mode
is


-- Message --------------------------------------------
subtype Message_szDescription_index is Integer range 1..10;
subtype Message_szDescription_array is adaasn1rtl.OctetBuffer(Message_szDescription_index);
type Message_szDescription is  record
    Data  : Message_szDescription_array;
end record;

type Message is record 
    msgId : adaasn1rtl.Asn1Int;
    myflag : adaasn1rtl.Asn1Int;
    value : adaasn1rtl.Asn1Real;
    szDescription : Message_szDescription;
    isReady : adaasn1rtl.Asn1Boolean;
end record;


ERR_MESSAGE_SZDESCRIPTION:constant Integer := 16; -- (SIZE(10))
function Message_szDescription_IsConstraintValid(val : Message_szDescription) return adaasn1rtl.ASN1_RESULT;

ERR_MESSAGE:constant Integer := 26; -- 
ERR_MESSAGE_MSGID:constant Integer := 1; -- 
ERR_MESSAGE_MYFLAG:constant Integer := 6; -- 
ERR_MESSAGE_VALUE:constant Integer := 11; -- 
ERR_MESSAGE_ISREADY:constant Integer := 21; -- 
function Message_IsConstraintValid(val : Message) return adaasn1rtl.ASN1_RESULT;

function Message_szDescription_Init  return Message_szDescription is
((Data => (others => 0)));
function Message_Init  return Message is
((msgId => 0, myflag => 0, value => 0.0000000000000000000E+000, szDescription => (Data => (others => 0)), isReady => False));
pragma Warnings (Off, "there are no others");
 
pragma Warnings (On, "there are no others");
private
   --# hide MY_MODULE;


end MY_MODULE;