/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>


#include "ApplicationProcess.h"



flag ApplicationProcess_ID_IsConstraintValid(const ApplicationProcess_ID* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 2047UL);
    *pErrCode = ret ? 0 :  ERR_APPLICATIONPROCESS_ID; 

	return ret;
}

void ApplicationProcess_ID_Initialize(ApplicationProcess_ID* pVal)
{
	(void)pVal;


	(*(pVal)) = 0;
}


