#ifndef GENERATED_ASN1SCC_ApplicationProcess_H
#define GENERATED_ASN1SCC_ApplicationProcess_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"

#ifdef  __cplusplus
extern "C" {
#endif


typedef asn1SccUint ApplicationProcess_ID;


#define ERR_APPLICATIONPROCESS_ID		31  /*(0 .. 2047)*/
flag ApplicationProcess_ID_IsConstraintValid(const ApplicationProcess_ID* pVal, int* pErrCode);

void ApplicationProcess_ID_Initialize(ApplicationProcess_ID* pVal);

 

/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */

 


#ifdef  __cplusplus
}

#endif

#endif
