/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>


#include "Dummy.h"



flag DummyType_IsConstraintValid(const DummyType* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) == 15UL);
    *pErrCode = ret ? 0 :  ERR_DUMMYTYPE; 

	return ret;
}

void DummyType_Initialize(DummyType* pVal)
{
	(void)pVal;


	(*(pVal)) = 15;
}


