/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>

#include "Dummy.h"
#include "ApplicationProcess.h"

#include "EventDefinition.h"


const asn1SccSint eventDefinition_ID_Size = 32;

flag EventDefinitionAuxiliaryData_IsConstraintValid(const EventDefinitionAuxiliaryData* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = DummyType_IsConstraintValid(pVal, pErrCode);

	return ret;
}

void EventDefinitionAuxiliaryData_Initialize(EventDefinitionAuxiliaryData* pVal)
{
	(void)pVal;


	(*(pVal)) = 15;
}


flag EventDefinition_ID_IsConstraintValid(const EventDefinition_ID* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = ((*(pVal)) <= 4294967295UL);
    *pErrCode = ret ? 0 :  ERR_EVENTDEFINITION_ID; 

	return ret;
}

void EventDefinition_ID_Initialize(EventDefinition_ID* pVal)
{
	(void)pVal;


	(*(pVal)) = 0;
}


