/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>

#include "EventDefinition.h"
#include "ApplicationProcess.h"

#include "PUS-5-1.h"



flag TM_5_1_InformativeEventReport_IsConstraintValid(const TM_5_1_InformativeEventReport* pVal, int* pErrCode)
{
    flag ret = TRUE;
    ret = EventDefinition_ID_IsConstraintValid((&(pVal->eventDefinition_ID)), pErrCode);
    if (ret) {
        ret = DummyType_IsConstraintValid((&(pVal->auxiliaryData)), pErrCode);
    }   /*COVERAGE_IGNORE*/

	return ret;
}

void TM_5_1_InformativeEventReport_Initialize(TM_5_1_InformativeEventReport* pVal)
{
	(void)pVal;



	/*set eventDefinition_ID */
	EventDefinition_ID_Initialize((&(pVal->eventDefinition_ID)));
	/*set auxiliaryData */
	DummyType_Initialize((&(pVal->auxiliaryData)));
}


