#ifndef GENERATED_ASN1SCC_PUS_5_1_H
#define GENERATED_ASN1SCC_PUS_5_1_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "EventDefinition.h"
#include "ApplicationProcess.h"

#ifdef  __cplusplus
extern "C" {
#endif


/*-- TM_5_1_InformativeEventReport --------------------------------------------*/
typedef struct {
    EventDefinition_ID eventDefinition_ID;
    DummyType auxiliaryData;

} TM_5_1_InformativeEventReport;

#define ERR_TM_5_1_INFORMATIVEEVENTREPORT		26  /**/
#define ERR_TM_5_1_INFORMATIVEEVENTREPORT_EVENTDEFINITION_ID_2		6  /**/
#define ERR_TM_5_1_INFORMATIVEEVENTREPORT_AUXILIARYDATA_2_2		21  /**/
flag TM_5_1_InformativeEventReport_IsConstraintValid(const TM_5_1_InformativeEventReport* pVal, int* pErrCode);

void TM_5_1_InformativeEventReport_Initialize(TM_5_1_InformativeEventReport* pVal);

 

/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */

 


#ifdef  __cplusplus
}

#endif

#endif
