
module AbstractMacros
open System
open System.Numerics
open CommonTypes
(*
WARNING !!!
Automatically generated file.

Generated by the C stg macros with the following command
../../parseStg2/bin/Debug/net5.0/parseStg2.exe backends.xml 4
*)
                

    [<AbstractClass>]
    type ITypeDefinition () =
        abstract member rtlModuleName : unit -> string;
        abstract member indentation : sStatement:string -> string;
        abstract member PrintSpecificationFile : sFileNameWithNoExtUpperCase:string -> sPackageName:string -> arrsIncludedModules:seq<string> -> arrsTypeAssignments:seq<string> -> arrsValueAssignments:seq<string> -> arrsPrototypes:seq<string> -> arrsUtilityDefines:seq<string> -> bHasEncodings:bool -> bXer:bool -> string;
        abstract member Define_TAS : sTypeDefinition:string -> arrsProcs:seq<string> -> string;
        abstract member PrintValueAssignment : sName:string -> sTypeDecl:string -> sValue:string -> string;
        abstract member Declare_Integer : unit -> string;
        abstract member Declare_PosInteger : unit -> string;
        abstract member Declare_IntegerNoRTL : unit -> string;
        abstract member Declare_PosIntegerNoRTL : unit -> string;
        abstract member Declare_Boolean : unit -> string;
        abstract member Declare_Real : unit -> string;
        abstract member Declare_Int8 : unit -> string;
        abstract member Declare_UInt8 : unit -> string;
        abstract member Declare_Int16 : unit -> string;
        abstract member Declare_UInt16 : unit -> string;
        abstract member Declare_Int32 : unit -> string;
        abstract member Declare_UInt32 : unit -> string;
        abstract member Declare_Int64 : unit -> string;
        abstract member Declare_UInt64 : unit -> string;
        abstract member Declare_Real32 : unit -> string;
        abstract member Declare_Real64 : unit -> string;
        abstract member Declare_BooleanNoRTL : unit -> string;
        abstract member Declare_RealNoRTL : unit -> string;
        abstract member Declare_Null : unit -> string;
        abstract member Declare_NullNoRTL : unit -> string;
        abstract member Declare_ObjectIdentifier : unit -> string;
        abstract member Declare_ObjectIdentifierNoRTL : unit -> string;
        abstract member Declare_Asn1LocalTime : unit -> string;
        abstract member Declare_Asn1UtcTime : unit -> string;
        abstract member Declare_Asn1LocalTimeWithTimeZone : unit -> string;
        abstract member Declare_Asn1Date : unit -> string;
        abstract member Declare_Asn1Date_LocalTime : unit -> string;
        abstract member Declare_Asn1Date_UtcTime : unit -> string;
        abstract member Declare_Asn1Date_LocalTimeWithTimeZone : unit -> string;
        abstract member Declare_Asn1LocalTimeNoRTL : unit -> string;
        abstract member Declare_Asn1UtcTimeNoRTL : unit -> string;
        abstract member Declare_Asn1LocalTimeWithTimeZoneNoRTL : unit -> string;
        abstract member Declare_Asn1DateNoRTL : unit -> string;
        abstract member Declare_Asn1Date_LocalTimeNoRTL : unit -> string;
        abstract member Declare_Asn1Date_UtcTimeNoRTL : unit -> string;
        abstract member Declare_Asn1Date_LocalTimeWithTimeZoneNoRTL : unit -> string;
        abstract member Define_SubType : sTypeDefinitionName:string -> soParentTypePackage:string option -> sParentType:string -> soNewRange:string option -> soExtraDefs:string option -> arrsAnnots:seq<string> -> string;
        abstract member Define_new_enumerated_item : td:FE_EnumeratedTypeDefinition -> sName:string -> nValue:BigInteger -> string;
        abstract member Define_new_enumerated_item_macro : td:FE_EnumeratedTypeDefinition -> sAsn1Name:string -> sCName:string -> string;
        abstract member Define_new_enumerated : td:FE_EnumeratedTypeDefinition -> arrsEnumNames:seq<string> -> arrsEnumNamesAndValues:seq<string> -> nIndexMax:BigInteger -> arrsResolvingMacros:seq<string> -> string;
        abstract member Define_subType_enumerated : td:FE_EnumeratedTypeDefinition -> prTd:FE_EnumeratedTypeDefinition -> soParentTypePackage:string option -> string;
        abstract member Define_new_enumerated_private : td:FE_EnumeratedTypeDefinition -> arrsValidEnumNames:seq<string> -> arrsEnumNames:seq<string> -> string;
        abstract member Define_subType_enumerated_private : td:FE_EnumeratedTypeDefinition -> prTd:FE_EnumeratedTypeDefinition -> arrsValidEnumNames:seq<string> -> arrsEnumNames:seq<string> -> string;
        abstract member Define_new_ia5string : td:FE_StringTypeDefinition -> nMin:BigInteger -> nMax:BigInteger -> nCMax:BigInteger -> arrnAlphaChars:seq<BigInteger> -> string;
        abstract member Define_subType_ia5string : td:FE_StringTypeDefinition -> prTd:FE_StringTypeDefinition -> soParentTypePackage:string option -> string;
        abstract member Define_new_octet_string : td:FE_SizeableTypeDefinition -> nMin:BigInteger -> nMax:BigInteger -> bFixedSize:bool -> arrsInvariants:seq<string> -> string;
        abstract member Define_subType_octet_string : td:FE_SizeableTypeDefinition -> prTd:FE_SizeableTypeDefinition -> soParentTypePackage:string option -> bFixedSize:bool -> string;
        abstract member Define_new_bit_string_named_bit : td:FE_SizeableTypeDefinition -> sTargetLangBitName:string -> sHexValue:string -> sComment:string -> string;
        abstract member Define_new_bit_string : td:FE_SizeableTypeDefinition -> nMin:BigInteger -> nMax:BigInteger -> bFixedSize:bool -> nMaxOctets:BigInteger -> arrsNamedBits:seq<string> -> arrsInvariants:seq<string> -> string;
        abstract member Define_subType_bit_string : td:FE_SizeableTypeDefinition -> prTd:FE_SizeableTypeDefinition -> soParentTypePackage:string option -> bFixedSize:bool -> string;
        abstract member Define_new_sequence_of : td:FE_SizeableTypeDefinition -> nMin:BigInteger -> nMax:BigInteger -> bFixedSize:bool -> sChildType:string -> soChildDefinition:string option -> arrsSizeClassDefinition:seq<string> -> arrsSizeObjDefinition:seq<string> -> arrsInvariants:seq<string> -> string;
        abstract member Define_subType_sequence_of : td:FE_SizeableTypeDefinition -> prTd:FE_SizeableTypeDefinition -> soParentTypePackage:string option -> bFixedSize:bool -> soChildDefinition:string option -> string;
        abstract member Define_new_sequence_child_bit : sName:string -> string;
        abstract member Define_new_sequence_child : sName:string -> sType:string -> bIsOptional:bool -> string;
        abstract member Define_new_sequence_save_pos_child : td:FE_SequenceTypeDefinition -> sName:string -> nMaxBytesInACN:BigInteger -> string;
        abstract member Define_new_sequence : td:FE_SequenceTypeDefinition -> arrsChildren:seq<string> -> arrsOptionalChildren:seq<string> -> arrsChildrenDefinitions:seq<string> -> arrsNullFieldsSavePos:seq<string> -> arrsSizeDefinition:seq<string> -> arrsInvariants:seq<string> -> string;
        abstract member Define_subType_sequence : td:FE_SequenceTypeDefinition -> prTd:FE_SequenceTypeDefinition -> soParentTypePackage:string option -> arrsOptionalChildren:seq<string> -> arrsExtraDefs:seq<string> -> string;
        abstract member Define_new_choice_child : sName:string -> sType:string -> sPresent:string -> string;
        abstract member Define_new_choice : td:FE_ChoiceTypeDefinition -> sChoiceIDForNone:string -> sFirstChildNamePresent:string -> arrsChildren:seq<string> -> arrsPresent:seq<string> -> arrsCombined:seq<string> -> nIndexMax:BigInteger -> arrsChildrenDefinitions:seq<string> -> arrsSizeDefinition:seq<string> -> string;
        abstract member Define_subType_choice : td:FE_ChoiceTypeDefinition -> prTd:FE_ChoiceTypeDefinition -> soParentTypePackage:string option -> string;
        abstract member Define_SubType_int_range : soParentTypePackage:string option -> sParentType:string -> noMin:BigInteger option -> noMax:BigInteger option -> string;


    [<AbstractClass>]
    type ISrcBody () =
        abstract member rtlModuleName : unit -> string;
        abstract member printSourceFile : sFileNameWithoutExtension:string -> arrsIncludedFiles:seq<string> -> arrsAdaUseTypes:seq<string> -> arrsValueAndTypeAssignments:seq<string> -> string;
        abstract member printTass : arrsAllProcs:seq<string> -> string;


    [<AbstractClass>]
    type IVariables () =
        abstract member PrintIntValue : nValue:BigInteger -> string;
        abstract member PrintRealValue : dValue:double -> string;
        abstract member PrintEnumValue : sValue:string -> string;
        abstract member PrintRefValue1 : sValue:string -> string;
        abstract member PrintRefValue2 : sModName:string -> sValue:string -> string;
        abstract member PrintStringValue : arrsVals:seq<string> -> arrsNullChars:seq<string> -> string;
        abstract member PrintSingleStringValue : sValue:string -> string;
        abstract member PrintLF : unit -> string;
        abstract member PrintCR : unit -> string;
        abstract member PrintHT : unit -> string;
        abstract member PrintStringValueNull : unit -> string;
        abstract member PrintCharValue : cValue:char -> string;
        abstract member PrintBooleanValue : bValue:bool -> string;
        abstract member PrintNullValue : unit -> string;
        abstract member PrintOctetStringValue : td:FE_SizeableTypeDefinition -> bIsFixedSize:bool -> arruBytes:seq<byte> -> nCount:BigInteger -> string;
        abstract member PrintBitStringValue : td:FE_SizeableTypeDefinition -> bIsFixedSize:bool -> arrsBits:seq<string> -> nCount:BigInteger -> arruBytes:seq<byte> -> nBytesCount:BigInteger -> string;
        abstract member PrintBitOrOctetStringValueAsCompoundLiteral : td:FE_SizeableTypeDefinition -> bIsFixedSize:bool -> arruBytes:seq<byte> -> nCount:BigInteger -> string;
        abstract member PrintOctetArrayAsCompoundLiteral : arruBytes:seq<byte> -> string;
        abstract member PrintBitArrayAsCompoundLiteral : arruBits:seq<byte> -> string;
        abstract member PrintObjectIdentifierValue : td:FE_PrimitiveTypeDefinition -> arrnValues:seq<BigInteger> -> nCount:BigInteger -> string;
        abstract member PrintObjectIdentifierValueAsCompoundLiteral : arrnValues:seq<BigInteger> -> nCount:BigInteger -> string;
        abstract member PrintTimeValueAsCompoundLiteral_Asn1LocalTime : td:FE_PrimitiveTypeDefinition -> tv:Asn1TimeValue -> string;
        abstract member PrintTimeValueAsCompoundLiteral_Asn1UtcTime : td:FE_PrimitiveTypeDefinition -> tv:Asn1TimeValue -> string;
        abstract member PrintTimeValueAsCompoundLiteral_Asn1LocalTimeWithTimeZone : td:FE_PrimitiveTypeDefinition -> tv:Asn1TimeValue -> tz:Asn1TimeZoneValue -> string;
        abstract member PrintTimeValueAsCompoundLiteral_Asn1Date : td:FE_PrimitiveTypeDefinition -> dt:Asn1DateValue -> string;
        abstract member PrintTimeValueAsCompoundLiteral_Asn1Date_LocalTime : td:FE_PrimitiveTypeDefinition -> dt:Asn1DateValue -> tv:Asn1TimeValue -> string;
        abstract member PrintTimeValueAsCompoundLiteral_Asn1Date_UtcTime : td:FE_PrimitiveTypeDefinition -> dt:Asn1DateValue -> tv:Asn1TimeValue -> string;
        abstract member PrintTimeValueAsCompoundLiteral_Asn1Date_LocalTimeWithTimeZone : td:FE_PrimitiveTypeDefinition -> dt:Asn1DateValue -> tv:Asn1TimeValue -> tz:Asn1TimeZoneValue -> string;
        abstract member PrintTimeValue_Asn1LocalTime : td:FE_PrimitiveTypeDefinition -> tv:Asn1TimeValue -> string;
        abstract member PrintTimeValue_Asn1UtcTime : td:FE_PrimitiveTypeDefinition -> tv:Asn1TimeValue -> string;
        abstract member PrintTimeValue_Asn1LocalTimeWithTimeZone : td:FE_PrimitiveTypeDefinition -> tv:Asn1TimeValue -> tz:Asn1TimeZoneValue -> string;
        abstract member PrintTimeValue_Asn1Date : td:FE_PrimitiveTypeDefinition -> dt:Asn1DateValue -> string;
        abstract member PrintTimeValue_Asn1Date_LocalTime : td:FE_PrimitiveTypeDefinition -> dt:Asn1DateValue -> tv:Asn1TimeValue -> string;
        abstract member PrintTimeValue_Asn1Date_UtcTime : td:FE_PrimitiveTypeDefinition -> dt:Asn1DateValue -> tv:Asn1TimeValue -> string;
        abstract member PrintTimeValue_Asn1Date_LocalTimeWithTimeZone : td:FE_PrimitiveTypeDefinition -> dt:Asn1DateValue -> tv:Asn1TimeValue -> tz:Asn1TimeZoneValue -> string;
        abstract member PrintSequenceValueChild : sName:string -> sInnerValue:string -> string;
        abstract member PrintSequenceValue_child_exists : sName:string -> sExistsBit:string -> string;
        abstract member PrintSequenceValue : td:FE_SequenceTypeDefinition -> sTasName:string -> arrsChildren:seq<string> -> arrsOptionalPresentFields:seq<string> -> string;
        abstract member PrintChoiceValue : sTasName:string -> sChildName:string -> sChildVal:string -> sChildNamePresent:string -> bUseUncheckedUnions:bool -> string;
        abstract member PrintValueAssignment : sName:string -> sTypeDecl:string -> sValue:string -> string;
        abstract member PrintSequenceOfValue : td:FE_SizeableTypeDefinition -> bIsFixedSize:bool -> nLength:BigInteger -> arrsInnerValues:seq<string> -> sDefValue:string -> string;


    [<AbstractClass>]
    type IEqual () =
        abstract member JoinItems : sPart:string -> soNestedPart:string option -> string;
        abstract member JoinItems2_ret : sPart:string -> sNestedPart:string -> string;
        abstract member JoinItems2_ret_result : sPart:string -> sNestedPart:string -> string;
        abstract member PrintEqualDefinitionPrimitive : sFuncName:string -> sTypeDefName:string -> string;
        abstract member PrintEqualDefinitionComposite : sFuncName:string -> sTypeDefName:string -> string;
        abstract member PrintEqualPrimitive : sFuncName:string -> sTypeDefName:string -> sContent:string -> string;
        abstract member PrintEqualComposite : sFuncName:string -> sTypeDefName:string -> sContent:string -> arrsLocalVars:seq<string> -> string;
        abstract member equalTypeAssignment_def : sVarName1:string -> sVarName2:string -> sStar:string -> sFuncName:string -> sTypeDefName:string -> string;
        abstract member equalTypeAssignment : sVarName1:string -> sVarName2:string -> sStar:string -> sFuncName:string -> sTypeDefName:string -> sContent:string -> arrsLocalVars:seq<string> -> bExpression:bool -> bUnreferenced:bool -> string;
        abstract member isEqual_Primitive : p1:string -> p2:string -> string;
        abstract member isEqual_String : p1:string -> p2:string -> string;
        abstract member isEqual_Real : p1:string -> p2:string -> string;
        abstract member isEqual_BitString : p1:string -> p2:string -> bIsFixedSize:bool -> nFixedSize:BigInteger -> string;
        abstract member isEqual_OctetString : p1:string -> p2:string -> bIsFixedSize:bool -> nFixedSize:BigInteger -> string;
        abstract member isObjectIdentifier_equal : p1:string -> p2:string -> string;
        abstract member isEqual_Choice_Child : sChoiceTypeDefName:string -> sCid:string -> sInnerStatement:string -> sTmpVarName1:string -> sTmpVarName2:string -> string;
        abstract member isEqual_Choice : p1:string -> p2:string -> sAccess:string -> arrsChildren:seq<string> -> string;
        abstract member isEqual_Sequence_child : p1:string -> p2:string -> sAcc:string -> bIsOptional:bool -> sChName:string -> soInnerStatement:string option -> string;
        abstract member isEqual_SequenceOf_var_size : p1:string -> p2:string -> sAcc:string -> i:string -> soInnerStatement:string option -> string;
        abstract member isEqual_SequenceOf_fix_size : p1:string -> p2:string -> sAcc:string -> i:string -> nFixedSize:BigInteger -> sInnerStatement:string -> string;
        abstract member call_base_type_func : p1:string -> p2:string -> sFuncName:string -> bIsP1Option:bool -> bIsP2Option:bool -> string;
        abstract member makeExpressionToStatement : sIsValidExp:string -> string;
        abstract member callChildEqualFunc : p1:string -> p2:string -> sChildEqualFuncName:string -> string;


    [<AbstractClass>]
    type IIsValid () =
        abstract member rtlModuleName : unit -> string;
        abstract member JoinItems : sPart:string -> soNestedPart:string option -> string;
        abstract member JoinTwoIfFirstOk : sStr1:string -> sStr2:string -> string;
        abstract member JoinItems2 : sPart:string -> sNestedPart:string -> string;
        abstract member always_true_statement : unit -> string;
        abstract member always_false_statement : sErrorCodeName:string -> string;
        abstract member makeExpressionToStatement0 : sIsValidExp:string -> string;
        abstract member convertVCBExpressionToStatementAndUpdateErrCode : sIsValidExp:string -> sErrCode:string -> string;
        abstract member convertVCBStatementToStatementAndUpdateErrCode : sStatement:string -> sErrCode:string -> string;
        abstract member convertVCBTRUEToStatementAndUpdateErrCode : unit -> string;
        abstract member convertVCBFalseToStatementAndUpdateErrCode : sErrCode:string -> string;
        abstract member EmitTypeAssignment_composite_def_err_code : sErrCode:string -> nErrValue:BigInteger -> arrsErrorCodeComments:seq<string> -> string;
        abstract member EmitTypeAssignment_composite_def : sVarName:string -> sStar:string -> sFuncName:string -> sTypeDefName:string -> arrsErrcodes:seq<string> -> string;
        abstract member EmitTypeAssignment_composite : sVarName:string -> sPtrPrefix:string -> sPtrSuffix:string -> sFuncName:string -> sTypeDefName:string -> sContent:string -> arrsAlphaFuncs:seq<string> -> arrsLocalVars:seq<string> -> bUnreferenced:bool -> string;
        abstract member GetEnumIndexByName : sEnumValuesArray:string -> sEnumValuesArrayCount:string -> sExp:string -> bBinarySearch:bool -> string;
        abstract member ExpEqual : sExp1:string -> sExp2:string -> string;
        abstract member ExpStringEqual : sExp1:string -> sExp2:string -> string;
        abstract member ExpGt : sExp1:string -> sExp2:string -> string;
        abstract member ExpGte : sExp1:string -> sExp2:string -> string;
        abstract member ExpLt : sExp1:string -> sExp2:string -> string;
        abstract member ExpLte : sExp1:string -> sExp2:string -> string;
        abstract member ExpOr : sExp1:string -> sExp2:string -> string;
        abstract member ExpAnd : sExp1:string -> sExp2:string -> string;
        abstract member ExpAndMulti : arrsExp:seq<string> -> string;
        abstract member ExpNot : sExp:string -> string;
        abstract member StrLen : sExp:string -> string;
        abstract member ArrayLen : sExp:string -> sAcc:string -> string;
        abstract member ExpressionToStatement : sExp1:string -> string;
        abstract member StatementOrStatement : sStat1:string -> sStat2:string -> string;
        abstract member ExpressionOrStatement : sExp1:string -> sStat2:string -> string;
        abstract member StatementOrExpression : sStat1:string -> sExp2:string -> string;
        abstract member StatementAndStatement : sStat1:string -> sStat2:string -> string;
        abstract member ExpressionAndStatement : sExp1:string -> sStat2:string -> string;
        abstract member StatementAndExpression : sStat1:string -> sExp2:string -> string;
        abstract member StatementNot : sStat:string -> string;
        abstract member StatementExceptStatement : sStat1:string -> sStat2:string -> string;
        abstract member ExpressionExceptStatement : sExp1:string -> sStat2:string -> string;
        abstract member StatementExceptExpression : sStat1:string -> sExp2:string -> string;
        abstract member StatementForLoop : p:string -> sAcc:string -> i:string -> bIsFixedSize:bool -> nFixedSize:BigInteger -> sInnerStatement:string -> string;
        abstract member Print_AlphabetCheckFunc : sFuncName:string -> arrsAlphaConBody:seq<string> -> string;
        abstract member SingleValConstraint : p:string -> v:string -> string;
        abstract member stringContainsChar : sStrVal:string -> p:string -> string;
        abstract member RangeConstraint : p:string -> v1:string -> v2:string -> bMin:bool -> bMax:bool -> string;
        abstract member RangeConstraint_val_MAX : p:string -> v:string -> bMin:bool -> string;
        abstract member RangeConstraint_MIN_val : p:string -> v:string -> bMax:bool -> string;
        abstract member AND_Constraint : sCon1:string -> sCon2:string -> string;
        abstract member OR_Constraint : sCon1:string -> sCon2:string -> string;
        abstract member AllExceptConstraint : sCon:string -> string;
        abstract member ExceptConstraint : sCon1:string -> sCon2:string -> string;
        abstract member callAlphaFunc : sFuncName:string -> p:string -> string;
        abstract member PrintMultipleConstraints : arrsConstraints:seq<string> -> string;
        abstract member Emit_type : arrsConstraints:seq<string> -> sErrCodeName:string -> string;
        abstract member call_base_type_func : p:string -> sFuncName:string -> soTypeCasting:string option -> string;
        abstract member call_base_type_func_exp : p:string -> sFuncName:string -> string;
        abstract member Sequence_OptionalChild : p:string -> sAcc:string -> sChName:string -> sInnerStatement:string -> string;
        abstract member Sequence_optional_child_always_present_or_absent : p:string -> sAcc:string -> sChName:string -> sErrCode:string -> sPresOrAbs:string -> string;
        abstract member Sequence_optional_child_always_present_or_absent_expr : p:string -> sAcc:string -> sChName:string -> sPresOrAbs:string -> string;
        abstract member Choice_OptionalChild : p:string -> sPLocal:string -> sAcc:string -> sChPresent:string -> sInnerStatement:string -> string;
        abstract member Choice_child_always_present_Exp : p:string -> sAcc:string -> sChPresent:string -> string;
        abstract member Choice_child_always_absent_Exp : p:string -> sAcc:string -> sChPresent:string -> string;
        abstract member choice_child : sChPresent:string -> sChildBody:string -> bAlwaysAbsent:bool -> sChildName:string -> string;
        abstract member choice : p:string -> sAccess:string -> arrsChildren:seq<string> -> sErrCodeForInvalidCase:string -> string;
        abstract member sequenceOf : p:string -> sAcc:string -> i:string -> bIsFixedSize:bool -> nFixedSize:BigInteger -> soIsValidSizeExp:string option -> soErrCode:string option -> soInnerStatement:string option -> string;
        abstract member sequenceOf2 : p:string -> sAcc:string -> i:string -> bIsFixedSize:bool -> nFixedSize:BigInteger -> sInnerStatement:string -> string;
        abstract member octet_var_string_equal : p:string -> sAccess:string -> nVarLength:BigInteger -> sOctArrayLiteral:string -> string;
        abstract member octet_fix_string_equal : p:string -> sAccess:string -> nFixedSize:BigInteger -> nVarLength:BigInteger -> sOctArrayLiteral:string -> string;
        abstract member bit_var_string_equal : p:string -> sAccess:string -> nVarLength:BigInteger -> sOctArrayLiteral:string -> sBitArrayLiteral:string -> string;
        abstract member bit_fix_string_equal : p:string -> sAccess:string -> nFixedSize:BigInteger -> nVarLength:BigInteger -> sOctArrayLiteral:string -> sBitArrayLiteral:string -> string;
        abstract member objId_equal : p:string -> sObjIdLiteral:string -> string;


    [<AbstractClass>]
    type IInit () =
        abstract member rtlModuleName : unit -> string;
        abstract member methodNameSuffix : unit -> string;
        abstract member initTypeAssignment_def : sVarName:string -> sStar:string -> sFuncName:string -> sTypeDefName:string -> string;
        abstract member initTypeAssignment : sVarName:string -> sPtrPrefix:string -> sPtrSuffix:string -> sFuncName:string -> sTypeDefName:string -> sContent:string -> arrsLocalVariables:seq<string> -> sDefaultInitValue:string -> arrsAnnots:seq<string> -> string;
        abstract member initInteger : sVal:string -> sValue:string -> bIsOptional:bool -> sResVar:string -> string;
        abstract member initReal : sVal:string -> dValue:double -> bIsOptional:bool -> sResVar:string -> string;
        abstract member initBoolean : sVal:string -> bValue:bool -> bIsOptional:bool -> sResVar:string -> string;
        abstract member initObjectIdentifier_valid : p:string -> sAcc:string -> sI:string -> nIntVal:BigInteger -> string;
        abstract member initObjectIdentifier : p:string -> sAcc:string -> nSize:BigInteger -> arrsValues:seq<string> -> string;
        abstract member init_Asn1LocalTime : p:string -> sAcc:string -> tv:Asn1TimeValue -> string;
        abstract member init_Asn1UtcTime : p:string -> sAcc:string -> tv:Asn1TimeValue -> string;
        abstract member init_Asn1LocalTimeWithTimeZone : p:string -> sAcc:string -> tv:Asn1TimeValue -> tz:Asn1TimeZoneValue -> string;
        abstract member init_Asn1Date : p:string -> sAcc:string -> dt:Asn1DateValue -> string;
        abstract member init_Asn1Date_LocalTime : p:string -> sAcc:string -> dt:Asn1DateValue -> tv:Asn1TimeValue -> string;
        abstract member init_Asn1Date_UtcTime : p:string -> sAcc:string -> dt:Asn1DateValue -> tv:Asn1TimeValue -> string;
        abstract member init_Asn1Date_LocalTimeWithTimeZone : p:string -> sAcc:string -> dt:Asn1DateValue -> tv:Asn1TimeValue -> tz:Asn1TimeZoneValue -> string;
        abstract member assignAny : p:string -> sValue:string -> sTypeDecl:string -> string;
        abstract member assignString : p:string -> sValue:string -> string;
        abstract member initIA5String : sPtr:string -> sValue:string -> bIsOptional:bool -> sResVar:string -> string;
        abstract member initEnumerated : sVal:string -> sValue:string -> sTypeDefName:string -> bIsOptional:bool -> sResVar:string -> string;
        abstract member initNull : sVal:string -> bIsOptional:bool -> sResVar:string -> string;
        abstract member initTestCaseIA5String : p:string -> sAcc:string -> nSize:BigInteger -> nMaxSizePlusOne:BigInteger -> i:string -> td:FE_StringTypeDefinition -> bAlpha:bool -> arrnAlphabetAsciiCodes:seq<BigInteger> -> nAlphabetLength:BigInteger -> bZero:bool -> sResVar:string -> string;
        abstract member initBitOrOctStringFromCompoundLiteral : p:string -> sCompLiteral:string -> string;
        abstract member initFixSizeBitOrOctString_bytei : p:string -> sAcc:string -> sI:string -> sByteHexVal:string -> string;
        abstract member initFixSizeBitOrOctString : p:string -> sAcc:string -> arrsBytes:seq<string> -> string;
        abstract member initFixVarSizeBitOrOctString : p:string -> sAcc:string -> nSize:BigInteger -> arrsBytes:seq<string> -> string;
        abstract member initTestCaseOctetString : p:string -> sAcc:string -> sArrayHolderName:string -> nSize:BigInteger -> i:string -> bIsFixedSize:bool -> bZero:bool -> nMinSize:BigInteger -> bZeroSizedArray:bool -> sResVar:string -> string;
        abstract member initTestCaseBitString : p:string -> sAcc:string -> sArrayHolderName:string -> nSize:BigInteger -> nSizeCeiled:BigInteger -> i:string -> bIsFixedSize:bool -> bZero:bool -> nMinSize:BigInteger -> bIsOptionalField:bool -> sResVar:string -> string;
        abstract member initSequence_pragma : p:string -> string;
        abstract member initFixedSequenceOf : arrsInnerValues:seq<string> -> string;
        abstract member initVarSizeSequenceOf : p:string -> sAcc:string -> nSize:BigInteger -> arrsInnerValues:seq<string> -> string;
        abstract member initTestCaseSizeSequenceOf_innerItem : bFirst:bool -> bLastItem:bool -> nCaseIdx:BigInteger -> sChildCaseInit:string -> i:string -> nCaseLen:BigInteger -> sResVar:string -> string;
        abstract member initTestCaseSizeSequenceOf : p:string -> sAcc:string -> sArrayHolderName:string -> noMinSize:BigInteger option -> nSize:BigInteger -> bIsFixedSize:bool -> arrsInnerItems:seq<string> -> bMultiCases:bool -> i:string -> sResVar:string -> string;
        abstract member initSequence_optionalChild : p:string -> sAcc:string -> sChName:string -> sPresentFlag:string -> sChildContent:string -> string;
        abstract member initSequence : arrsInnerValues:seq<string> -> string;
        abstract member initSequence_emptySeq : p:string -> string;
        abstract member initTestCase_sequence_child : p:string -> sAcc:string -> sChName:string -> sChildContent:string -> bOptional:bool -> sInitExpr:string -> string;
        abstract member initTestCase_sequence_child_opt : p:string -> sAcc:string -> sChName:string -> sChildTypedef:string -> sResVar:string -> string;
        abstract member initChoice : p:string -> sAcc:string -> sChildContent:string -> sChildID:string -> sChildName:string -> sChildTypeName:string -> sChoiceTypeName:string -> sChildTempVarName:string -> sChildTempDefaultInit:string -> bComponentTempInit:bool -> string;
        abstract member initTestCase_choice_child : p:string -> sAcc:string -> sChildContent:string -> sChildID:string -> sChildName:string -> sChildTypeName:string -> sChoiceTypeName:string -> sChildTempVarName:string -> sChildTempDefaultInit:string -> bIsOptional:bool -> sResVar:string -> string;
        abstract member initChildWithInitFunc : p:string -> sChildInitFuncName:string -> string;
        abstract member initBitStringAtPos : sVarName:string -> sStar:string -> sFuncName:string -> sTypeDefName:string -> sNamedBit:string -> nZeroBasedByteIndex:BigInteger -> sHexByteMax:string -> nZeroBasedBitIndex:BigInteger -> string;
        abstract member initBitStringAtPos_def : sVarName:string -> sStar:string -> sFuncName:string -> sTypeDefName:string -> sNamedBit:string -> string;
        abstract member initTypeConstant_def : sTypeDecl:string -> sConstantName:string -> sValue:string -> string;
        abstract member initTypeConstant_body : sTypeDecl:string -> sConstantName:string -> sValue:string -> string;
        abstract member initFixSizeOctetString : sTypeDefName:string -> nMax:BigInteger -> bZeroSizedArray:bool -> string;
        abstract member initVarSizeOctetString : sTypeDefName:string -> nMin:BigInteger -> nMax:BigInteger -> string;
        abstract member initFixSizeBitString : sTypeDefName:string -> nMax:BigInteger -> nMaxOctets:BigInteger -> string;
        abstract member initVarSizeBitString : sTypeDefName:string -> nMin:BigInteger -> nMax:BigInteger -> nMaxOctets:BigInteger -> string;
        abstract member initFixSizeSequenceOfExpr : sTypeDefName:string -> nMax:BigInteger -> sChildExp:string -> string;
        abstract member initVarSizeSequenceOfExpr : sTypeDefName:string -> nMin:BigInteger -> nMax:BigInteger -> sChildExp:string -> string;
        abstract member initObjectIdentifierAsExpr : unit -> string;
        abstract member init_Asn1LocalTimeExpr : unit -> string;
        abstract member init_Asn1UtcTimeExpr : unit -> string;
        abstract member init_Asn1LocalTimeWithTimeZoneExpr : unit -> string;
        abstract member init_Asn1DateExpr : unit -> string;
        abstract member init_Asn1Date_LocalTimeExpr : unit -> string;
        abstract member init_Asn1Date_UtcTimeExpr : unit -> string;
        abstract member init_Asn1Date_LocalTimeWithTimeZoneExpr : unit -> string;
        abstract member initSequenceChildExpr : sChildName:string -> sChildExpr:string -> bIsOptional:bool -> bIsAbsent:bool -> string;
        abstract member initSequenceOptionalChildExpr : sChildName:string -> nPresenceBit:BigInteger -> string;
        abstract member initSequenceExpr : sTypeDefName:string -> arrsChildren:seq<string> -> arrsOptionalChildren:seq<string> -> string;
        abstract member initChoiceExpr : sChildName:string -> sChildKind:string -> sChildExpr:string -> string;


    [<AbstractClass>]
    type IUper () =
        abstract member rtlModuleName : unit -> string;
        abstract member call_base_type_func : p:string -> sFuncName:string -> codec:Codec -> string;
        abstract member EmitTypeAssignment_def_err_code : sErrCode:string -> nErrValue:BigInteger -> string;
        abstract member EmitTypeAssignment_def : sVarName:string -> sStar:string -> sFuncName:string -> sTypeDefName:string -> arrsErrcodes:seq<string> -> bEmptyEncodingSpace:bool -> nMaxBytesInPER:BigInteger -> nMaxBitsInPER:BigInteger -> soSparkAnnotations:string option -> bReqBytesForEncodingIsZero:bool -> codec:Codec -> string;
        abstract member EmitTypeAssignment : sVarName:string -> sStar:string -> sFuncName:string -> soIValidFuncName:string option -> sTypeDefName:string -> arrsLocalVariables:seq<string> -> sContent:string -> soSparkAnnotations:string option -> sInitialExp:string -> bReqBytesForEncodingIsZero:bool -> bBsIsUnreferenced:bool -> bVarNameIsUnreferenced:bool -> soInitFuncName:string option -> arrsAnnots:seq<string> -> arrsPrecond:seq<string> -> soPostcond:string option -> codec:Codec -> string;
        abstract member InternalItem_oct_str : p:string -> sAcc:string -> i:string -> sErrCode:string -> codec:Codec -> string;
        abstract member InternalItem_string_with_alpha : p:string -> sErrCode:string -> td:FE_StringTypeDefinition -> i:string -> nLastItemIndex:BigInteger -> arrnAlphabetAsciiCodes:seq<BigInteger> -> nAlphabetLength:BigInteger -> nCharIndexSize:BigInteger -> codec:Codec -> string;
        abstract member InternalItem_string_no_alpha : p:string -> sErrCode:string -> i:string -> codec:Codec -> string;
        abstract member IntFullyConstraint : p:string -> nMin:BigInteger -> nMax:BigInteger -> nBits:BigInteger -> sSsuffix:string -> sErrCode:string -> codec:Codec -> string;
        abstract member IntFullyConstraintPos : p:string -> nMin:BigInteger -> nMax:BigInteger -> nBits:BigInteger -> sSsuffix:string -> sErrCode:string -> soRangeAssert:string option -> codec:Codec -> string;
        abstract member IntUnconstrained : p:string -> sErrCode:string -> bCoverageIgnore:bool -> codec:Codec -> string;
        abstract member IntUnconstrainedMax : p:string -> nMax:BigInteger -> soCheckExp:string option -> sErrCode:string -> codec:Codec -> string;
        abstract member IntSemiConstraint : p:string -> nMin:BigInteger -> sErrCode:string -> codec:Codec -> string;
        abstract member IntSemiConstraintPos : p:string -> nMin:BigInteger -> sErrCode:string -> codec:Codec -> string;
        abstract member IntNoneRequired : p:string -> sConst:string -> sErrCode:string -> codec:Codec -> string;
        abstract member IntRootExt : p:string -> nMin:BigInteger -> sRootBaseConstraint:string -> sIntBody:string -> sErrCode:string -> codec:Codec -> string;
        abstract member IntRootExt2 : p:string -> nMin:BigInteger -> sRootBaseConstraint:string -> sIntBody:string -> sErrCode:string -> codec:Codec -> string;
        abstract member Boolean : p:string -> sErrCode:string -> codec:Codec -> string;
        abstract member Real : p:string -> sSuffix:string -> sErrCode:string -> codec:Codec -> string;
        abstract member ObjectIdentifier : p:string -> sErrCode:string -> codec:Codec -> string;
        abstract member RelativeOID : p:string -> sErrCode:string -> codec:Codec -> string;
        abstract member Time : p:string -> sTimeSubType:string -> sErrCode:string -> codec:Codec -> string;
        abstract member Enumerated_item : p:string -> sName:string -> nIndex:BigInteger -> nLastItemIndex:BigInteger -> codec:Codec -> string;
        abstract member Enumerated : p:string -> td:FE_EnumeratedTypeDefinition -> arrsItem:seq<string> -> nMin:BigInteger -> nMax:BigInteger -> nBits:BigInteger -> sErrCode:string -> nLastItemIndex:BigInteger -> sFirstItemName:string -> codec:Codec -> string;
        abstract member Enumerated_no_switch : p:string -> td:FE_EnumeratedTypeDefinition -> sErrCode:string -> sEnumIndex:string -> nLastItemIndex:BigInteger -> sFirstItemName:string -> codec:Codec -> string;
        abstract member choice_child : p:string -> sAcc:string -> sChildID:string -> nChildIndex:BigInteger -> nIndexSizeInBits:BigInteger -> nLastItemIndex:BigInteger -> sChildContent:string -> sChildName:string -> sChildTypeDef:string -> sChoiceTypeName:string -> sChildInitExpr:string -> bIsSequence:bool -> bIsEnum:bool -> codec:Codec -> string;
        abstract member choice : p:string -> sAcc:string -> arrsChildren:seq<string> -> nLastItemIndex:BigInteger -> sChoiceIndexName:string -> sErrCode:string -> td:FE_ChoiceTypeDefinition -> nIndexSizeInBits:BigInteger -> bIntroSnap:bool -> codec:Codec -> string;
        abstract member sequence_presence_bit : p:string -> sAcc:string -> sChName:string -> soExistVar:string option -> sErrCode:string -> codec:Codec -> string;
        abstract member sequence_presence_bit_fix : p:string -> sAcc:string -> sChName:string -> soExistVar:string option -> sErrCode:string -> sVal:string -> codec:Codec -> string;
        abstract member sequence_mandatory_child : sChName:string -> sChildContent:string -> codec:Codec -> string;
        abstract member sequence_optional_child : p:string -> sAcc:string -> sChName:string -> sChildContent:string -> soExistVar:string option -> soChildExpr:string option -> sChildTypedef:string -> codec:Codec -> string;
        abstract member sequence_default_child : p:string -> sAcc:string -> sChName:string -> sChildContent:string -> soExistVar:string option -> soChildExpr:string option -> sChildTypedef:string -> sInitWithDefaultValue:string -> codec:Codec -> string;
        abstract member sequence_build : p:string -> sTypeDefName:string -> bIsOptional:bool -> arrsChildren:seq<string> -> string;
        abstract member str_FixedSize : p:string -> sTasName:string -> i:string -> sInternalItem:string -> nFixedSize:BigInteger -> nIntItemMinSize:BigInteger -> nIntItemMaxSize:BigInteger -> nAlignSize:BigInteger -> soInitExpr:string option -> bIntroSnap:bool -> soCallAux:string option -> codec:Codec -> string;
        abstract member str_VarSize : p:string -> sPIden:string -> sTasName:string -> i:string -> sInternalItem:string -> nSizeMin:BigInteger -> nSizeMax:BigInteger -> nSizeInBits:BigInteger -> nIntItemMinSize:BigInteger -> nIntItemMaxSize:BigInteger -> nAlignSize:BigInteger -> soInitExpr:string option -> soCallAux:string option -> codec:Codec -> string;
        abstract member seqOf_FixedSize : p:string -> sTasName:string -> i:string -> sInternalItem:string -> nFixedSize:BigInteger -> nIntItemMinSize:BigInteger -> nIntItemMaxSize:BigInteger -> nAlignSize:BigInteger -> sChildInitExpr:string -> soCallAux:string option -> codec:Codec -> string;
        abstract member seqOf_VarSize : p:string -> sAcc:string -> sTasName:string -> i:string -> sInternalItem:string -> nSizeMin:BigInteger -> nSizeMax:BigInteger -> nSizeInBits:BigInteger -> nIntItemMinSize:BigInteger -> nIntItemMaxSize:BigInteger -> nAlignSize:BigInteger -> sChildInitExpr:string -> sErrCode:string -> nAbsOffset:BigInteger -> nRemainingMinBits:BigInteger -> nLevel:BigInteger -> nIx:BigInteger -> nOffset:BigInteger -> bIntroSnap:bool -> soCallAux:string option -> codec:Codec -> string;
        abstract member octet_FixedSize : sTypeDefName:string -> p:string -> sAcc:string -> nFixedSize:BigInteger -> codec:Codec -> string;
        abstract member octet_VarSize : sTypeDefName:string -> p:string -> sAcc:string -> nSizeMin:BigInteger -> nSizeMax:BigInteger -> nSizeInBits:BigInteger -> sErrCode:string -> codec:Codec -> string;
        abstract member bitString_FixSize : sTypeDefName:string -> p:string -> sAcc:string -> nFixedSize:BigInteger -> sErrCode:string -> codec:Codec -> string;
        abstract member bitString_VarSize : sTypeDefName:string -> p:string -> sAcc:string -> nSizeMin:BigInteger -> nSizeMax:BigInteger -> sErrCode:string -> nSizeInBits:BigInteger -> codec:Codec -> string;
        abstract member FixedSize_Fragmentation_sqf_64K : p:string -> sAcc:string -> sCurOffset:string -> sCurBlockSize:string -> sBlockIndex:string -> nBlocks64K:BigInteger -> sInternalItem:string -> sBLI:string -> sRemainingItemsVar:string -> bIsBitStringType:bool -> sErrCodeName:string -> codec:Codec -> string;
        abstract member FixedSize_Fragmentation_sqf_small_block : p:string -> sAcc:string -> sInternalItem:string -> nBlockSize:BigInteger -> sBlockId:string -> sCurOffset:string -> sCurBlockSize:string -> sBLI:string -> sRemainingItemsVar:string -> bIsBitStringType:bool -> sErrCodeName:string -> codec:Codec -> string;
        abstract member FixedSize_Fragmentation_sqf_remaining : p:string -> sAcc:string -> sInternalItem:string -> bRemainingItemsWithinByte:bool -> nRemainingItemsVar:BigInteger -> sCurOffset:string -> sBLI:string -> sRemainingItemsVar:string -> bIsBitStringType:bool -> sErrCodeName:string -> codec:Codec -> string;
        abstract member FixedSize_Fragmentation_sqf : p:string -> sAcc:string -> arrsEncodingParts:seq<string> -> nFixedSize:BigInteger -> bIsBitStringType:bool -> codec:Codec -> string;
        abstract member Fragmentation_sqf : p:string -> sAcc:string -> sInternalItem:string -> nIntItemMaxSize:BigInteger -> nSizeMin:BigInteger -> nSizeMax:BigInteger -> nRequiredBitsForUPerEncoding:BigInteger -> bIsVariableSize:bool -> sErrCodeName:string -> sRemainingItemsVar:string -> sCurBlockSize:string -> sBlockIndex:string -> sCurOffset:string -> sBLJ:string -> sBLI:string -> sLengthTmp:string -> bIsBitStringType:bool -> bIsAsciiString:bool -> codec:Codec -> string;
        abstract member octet_string_containing_func : p:string -> sFuncName:string -> sReqBytesForUperEncoding:string -> nBits:BigInteger -> nMinSize:BigInteger -> nMaxSize:BigInteger -> codec:Codec -> string;
        abstract member bit_string_containing_func : p:string -> sFuncName:string -> sReqBytesForUperEncoding:string -> sReqBitsForUperEncoding:string -> nBits:BigInteger -> nMinSize:BigInteger -> nMaxSize:BigInteger -> codec:Codec -> string;
        abstract member sparkAnnotations : sTypeDefName:string -> codec:Codec -> string;
        abstract member Null_declare : p:string -> string;
        abstract member decode_nullType : p:string -> string;
        abstract member decode_empty_sequence_emptySeq : p:string -> string;
        abstract member JoinItems : sPart:string -> soNestedPart:string option -> string;
        abstract member update_array_item : p:string -> sI:string -> sExpr:string -> string;
        abstract member InternalItem_bit_str : p:string -> i:string -> sErrCode:string -> codec:Codec -> string;


    [<AbstractClass>]
    type IAcn () =
        abstract member getStringSize : p:string -> string;
        abstract member getSizeableSize : p:string -> sAcc:string -> bIsUnsigned:bool -> string;
        abstract member EmitTypeAssignment_def_err_code : sErrCode:string -> nErrValue:BigInteger -> soErrorCodeComment:string option -> string;
        abstract member EmitAcnParameter : sName:string -> sType:string -> string;
        abstract member EmitTypeAssignment_primitive_def : sVarName:string -> sStar:string -> sFuncName:string -> sTypeDefName:string -> arrsErrcodes:seq<string> -> bEmptyEncodingSpace:bool -> nMaxBytesInACN:BigInteger -> nMaxBitsInACN:BigInteger -> arrsAcnPrms:seq<string> -> soSparkAnnotations:string option -> codec:Codec -> string;
        abstract member EmitTypeAssignment_primitive : sVarName:string -> sStar:string -> sFuncName:string -> soIValidFuncName:string option -> sTypeDefName:string -> arrsLocalVariables:seq<string> -> sContent:string -> soSparkAnnotations:string option -> sInitialExp:string -> arrsAcnPrms:seq<string> -> arrsAcnParamNames:seq<string> -> bEmptyEncodingSpace:bool -> bBsIsUnreferenced:bool -> bVarNameIsUnreferenced:bool -> soInitFuncName:string option -> arrsAnnots:seq<string> -> arrsPrecond:seq<string> -> soPostcond:string option -> codec:Codec -> string;
        abstract member alignToNext : sMainBody:string -> sAlignmentValue:string -> nAlignmentValue:BigInteger -> nAbsOffset:BigInteger -> nRemainingMinBits:BigInteger -> nLevel:BigInteger -> nIx:BigInteger -> nOffset:BigInteger -> codec:Codec -> string;
        abstract member PositiveInteger_ConstSize : p:string -> sSsuffix:string -> sErrCode:string -> nFixedSize:BigInteger -> soMF:string option -> soMFM:string option -> nUperMin:BigInteger -> nUperMax:BigInteger -> codec:Codec -> string;
        abstract member PositiveInteger_ConstSize_8 : p:string -> sSsuffix:string -> sErrCode:string -> soMF:string option -> soMFM:string option -> nUperMin:BigInteger -> nUperMax:BigInteger -> codec:Codec -> string;
        abstract member PositiveInteger_ConstSize_big_endian_16 : p:string -> sSsuffix:string -> sErrCode:string -> soMF:string option -> soMFM:string option -> nUperMin:BigInteger -> nUperMax:BigInteger -> codec:Codec -> string;
        abstract member PositiveInteger_ConstSize_big_endian_32 : p:string -> sSsuffix:string -> sErrCode:string -> soMF:string option -> soMFM:string option -> nUperMin:BigInteger -> nUperMax:BigInteger -> codec:Codec -> string;
        abstract member PositiveInteger_ConstSize_big_endian_64 : p:string -> sSsuffix:string -> sErrCode:string -> soMF:string option -> soMFM:string option -> nUperMin:BigInteger -> nUperMax:BigInteger -> codec:Codec -> string;
        abstract member PositiveInteger_ConstSize_little_endian_16 : p:string -> sSsuffix:string -> sErrCode:string -> soMF:string option -> soMFM:string option -> nUperMin:BigInteger -> nUperMax:BigInteger -> codec:Codec -> string;
        abstract member PositiveInteger_ConstSize_little_endian_32 : p:string -> sSsuffix:string -> sErrCode:string -> soMF:string option -> soMFM:string option -> nUperMin:BigInteger -> nUperMax:BigInteger -> codec:Codec -> string;
        abstract member PositiveInteger_ConstSize_little_endian_64 : p:string -> sSsuffix:string -> sErrCode:string -> soMF:string option -> soMFM:string option -> nUperMin:BigInteger -> nUperMax:BigInteger -> codec:Codec -> string;
        abstract member PositiveInteger_VarSize_LengthEmbedded : p:string -> sSsuffix:string -> sErrCode:string -> soMF:string option -> soMFM:string option -> nUperMin:BigInteger -> codec:Codec -> string;
        abstract member TwosComplement_ConstSize : p:string -> sSsuffix:string -> sErrCode:string -> soMF:string option -> soMFM:string option -> nFixedSize:BigInteger -> nUperMin:BigInteger -> nUperMax:BigInteger -> codec:Codec -> string;
        abstract member TwosComplement_ConstSize_8 : p:string -> sSsuffix:string -> sErrCode:string -> soMF:string option -> soMFM:string option -> nUperMin:BigInteger -> nUperMax:BigInteger -> codec:Codec -> string;
        abstract member TwosComplement_ConstSize_big_endian_16 : p:string -> sSsuffix:string -> sErrCode:string -> soMF:string option -> soMFM:string option -> nUperMin:BigInteger -> nUperMax:BigInteger -> codec:Codec -> string;
        abstract member TwosComplement_ConstSize_big_endian_32 : p:string -> sSsuffix:string -> sErrCode:string -> soMF:string option -> soMFM:string option -> nUperMin:BigInteger -> nUperMax:BigInteger -> codec:Codec -> string;
        abstract member TwosComplement_ConstSize_big_endian_64 : p:string -> sSsuffix:string -> sErrCode:string -> soMF:string option -> soMFM:string option -> nUperMin:BigInteger -> nUperMax:BigInteger -> codec:Codec -> string;
        abstract member TwosComplement_ConstSize_little_endian_16 : p:string -> sSsuffix:string -> sErrCode:string -> soMF:string option -> soMFM:string option -> nUperMin:BigInteger -> nUperMax:BigInteger -> codec:Codec -> string;
        abstract member TwosComplement_ConstSize_little_endian_32 : p:string -> sSsuffix:string -> sErrCode:string -> soMF:string option -> soMFM:string option -> nUperMin:BigInteger -> nUperMax:BigInteger -> codec:Codec -> string;
        abstract member TwosComplement_ConstSize_little_endian_64 : p:string -> sSsuffix:string -> sErrCode:string -> soMF:string option -> soMFM:string option -> nUperMin:BigInteger -> nUperMax:BigInteger -> codec:Codec -> string;
        abstract member TwosComplement_VarSize_LengthEmbedded : p:string -> sSsuffix:string -> sErrCode:string -> soMF:string option -> soMFM:string option -> codec:Codec -> string;
        abstract member BCD_ConstSize : p:string -> sSsuffix:string -> sErrCode:string -> soMF:string option -> soMFM:string option -> nUperMin:BigInteger -> nUperMax:BigInteger -> nNibbles:BigInteger -> codec:Codec -> string;
        abstract member BCD_VarSize_LengthEmbedded : p:string -> sSsuffix:string -> sErrCode:string -> soMF:string option -> soMFM:string option -> codec:Codec -> string;
        abstract member BCD_VarSize_NullTerminated : p:string -> sSsuffix:string -> sErrCode:string -> soMF:string option -> soMFM:string option -> nUperMin:BigInteger -> nUperMax:BigInteger -> codec:Codec -> string;
        abstract member ASCII_ConstSize : p:string -> sSsuffix:string -> sErrCode:string -> soMF:string option -> soMFM:string option -> nUperMin:BigInteger -> nUperMax:BigInteger -> nSizeInBytes:BigInteger -> codec:Codec -> string;
        abstract member ASCII_VarSize_LengthEmbedded : p:string -> sSsuffix:string -> sErrCode:string -> soMF:string option -> soMFM:string option -> codec:Codec -> string;
        abstract member ASCII_VarSize_NullTerminated : p:string -> sSsuffix:string -> sErrCode:string -> soMF:string option -> soMFM:string option -> nUperMin:BigInteger -> nUperMax:BigInteger -> arruNullBytes:seq<byte> -> codec:Codec -> string;
        abstract member ASCII_UINT_ConstSize : p:string -> sSsuffix:string -> sErrCode:string -> soMF:string option -> soMFM:string option -> nUperMin:BigInteger -> nUperMax:BigInteger -> nSizeInBytes:BigInteger -> codec:Codec -> string;
        abstract member ASCII_UINT_VarSize_NullTerminated : p:string -> sSsuffix:string -> sErrCode:string -> soMF:string option -> soMFM:string option -> nUperMin:BigInteger -> nUperMax:BigInteger -> arruNullBytes:seq<byte> -> codec:Codec -> string;
        abstract member Real_32_big_endian : p:string -> sSuffix:string -> sErrCode:string -> codec:Codec -> string;
        abstract member Real_64_big_endian : p:string -> sErrCode:string -> codec:Codec -> string;
        abstract member Real_32_little_endian : p:string -> sSuffix:string -> sErrCode:string -> codec:Codec -> string;
        abstract member Real_64_little_endian : p:string -> sErrCode:string -> codec:Codec -> string;
        abstract member Boolean : p:string -> ptr:string -> bEncValIsTrue:bool -> nSize:BigInteger -> arruTrueValueAsByteArray:seq<byte> -> arruFalseValueAsByteArray:seq<byte> -> arrsBits:seq<string> -> sErrCode:string -> codec:Codec -> string;
        abstract member BooleanTrueFalse : p:string -> ptr:string -> nSize:BigInteger -> arruTrueValueAsByteArray:seq<byte> -> arruFalseValueAsByteArray:seq<byte> -> arrsTrueBits:seq<string> -> arrsFalseBits:seq<string> -> sErrCode:string -> codec:Codec -> string;
        abstract member Null_declare : p:string -> string;
        abstract member Null_pattern : p:string -> arruNullValueAsByteArray:seq<byte> -> nSize:BigInteger -> arrsBits:seq<string> -> sErrCode:string -> bSavePosition:bool -> codec:Codec -> string;
        abstract member Null_pattern2 : p:string -> arruNullValueAsByteArray:seq<byte> -> nSize:BigInteger -> arrsBits:seq<string> -> sErrCode:string -> bSavePosition:bool -> codec:Codec -> string;
        abstract member Enumerated_item : p:string -> sName:string -> sEnumHolder:string -> nItemIdx:BigInteger -> sItemVal:string -> sIntVal:string -> codec:Codec -> string;
        abstract member EnumeratedEncIdx : p:string -> td:FE_EnumeratedTypeDefinition -> arrsItem:seq<string> -> sActualCodecFunc:string -> sIntVal:string -> codec:Codec -> string;
        abstract member EnumeratedEncValues : p:string -> td:FE_EnumeratedTypeDefinition -> arrsItem:seq<string> -> sActualCodecFunc:string -> sErrCode:string -> sFirstItemName:string -> sIntVal:string -> codec:Codec -> string;
        abstract member EnumeratedEncValues_no_switch : p:string -> td:FE_EnumeratedTypeDefinition -> sActualCodecFunc:string -> sErrCode:string -> sFirstItemName:string -> sIntVal:string -> sEnumIndex:string -> nLastItemIndex:BigInteger -> bEncodeValues:bool -> codec:Codec -> string;
        abstract member Acn_String_Ascii_FixSize : p:string -> sErrCode:string -> nAsn1Max:BigInteger -> codec:Codec -> string;
        abstract member Acn_String_Ascii_Null_Terminated : p:string -> sErrCode:string -> nAsn1Max:BigInteger -> arruNullBytes:seq<byte> -> codec:Codec -> string;
        abstract member Acn_String_Ascii_External_Field_Determinant : p:string -> sErrCode:string -> nAsn1Max:BigInteger -> sExtFld:string -> codec:Codec -> string;
        abstract member Acn_String_Ascii_Internal_Field_Determinant : p:string -> sErrCode:string -> nAsn1Max:BigInteger -> nAsn1Min:BigInteger -> nInternalLengthDeterminantSizeInBits:BigInteger -> codec:Codec -> string;
        abstract member Acn_String_CharIndex_FixSize : p:string -> sErrCode:string -> nAsn1Max:BigInteger -> arrnAlphabetAsciiCodes:seq<BigInteger> -> nCharSetSize:BigInteger -> td:FE_StringTypeDefinition -> nCharSize:BigInteger -> codec:Codec -> string;
        abstract member Acn_String_CharIndex_External_Field_Determinant : p:string -> sErrCode:string -> nAsn1Max:BigInteger -> arrnAlphabetAsciiCodes:seq<BigInteger> -> nCharSetSize:BigInteger -> sExtFld:string -> td:FE_StringTypeDefinition -> nCharSize:BigInteger -> codec:Codec -> string;
        abstract member Acn_IA5String_CharIndex_External_Field_Determinant : p:string -> sErrCode:string -> nAsn1Max:BigInteger -> sExtFld:string -> td:FE_StringTypeDefinition -> nCharSize:BigInteger -> nRemainingBits:BigInteger -> codec:Codec -> string;
        abstract member oct_external_field : sTypedefName:string -> p:string -> sAcc:string -> noSizeMin:BigInteger option -> nSizeMax:BigInteger -> sExtFld:string -> bIsUnsigned:bool -> nAlignSize:BigInteger -> sErrCode:string -> codec:Codec -> string;
        abstract member oct_external_field_fix_size : sTypedefName:string -> p:string -> sAcc:string -> noSizeMin:BigInteger option -> nSizeMax:BigInteger -> sExtFld:string -> bIsUnsigned:bool -> nAlignSize:BigInteger -> sErrCode:string -> codec:Codec -> string;
        abstract member seqOf_VarSize : p:string -> sAcc:string -> sTasName:string -> i:string -> sInternalItem:string -> nSizeMin:BigInteger -> nSizeMax:BigInteger -> nSizeInBits:BigInteger -> nIntItemMinSize:BigInteger -> nIntItemMaxSize:BigInteger -> nAlignSize:BigInteger -> sChildInitExpr:string -> sErrCode:string -> nAbsOffset:BigInteger -> nRemainingMinBits:BigInteger -> nLevel:BigInteger -> nIx:BigInteger -> nOffset:BigInteger -> bIntroSnap:bool -> soCallAux:string option -> codec:Codec -> string;
        abstract member sqf_external_field : sTypeDefName:string -> p:string -> sAcc:string -> i:string -> sInternalItem:string -> noSizeMin:BigInteger option -> nSizeMax:BigInteger -> sExtFld:string -> bIsUnsigned:bool -> nAlignSize:BigInteger -> sErrCode:string -> nIntItemMinSize:BigInteger -> nIntItemMaxSize:BigInteger -> sChildInitExpr:string -> bIntroSnap:bool -> soCallAux:string option -> codec:Codec -> string;
        abstract member sqf_external_field_fix_size : sTypeDefName:string -> p:string -> sAcc:string -> i:string -> sInternalItem:string -> noSizeMin:BigInteger option -> nSizeMax:BigInteger -> sExtFld:string -> bIsUnsigned:bool -> nAlignSize:BigInteger -> sErrCode:string -> nIntItemMinSize:BigInteger -> nIntItemMaxSize:BigInteger -> sChildInitExpr:string -> bIntroSnap:bool -> soCallAux:string option -> codec:Codec -> string;
        abstract member oct_sqf_null_terminated : p:string -> sAcc:string -> i:string -> sInternalItem:string -> noSizeMin:BigInteger option -> nSizeMax:BigInteger -> arruNullBytes:seq<byte> -> nBitPatternLength:BigInteger -> sErrCode:string -> nIntItemMinSize:BigInteger -> nIntItemMaxSize:BigInteger -> codec:Codec -> string;
        abstract member bit_string_external_field : sTypeDefName:string -> p:string -> sErrCode:string -> sAcc:string -> noSizeMin:BigInteger option -> nSizeMax:BigInteger -> sExtFld:string -> codec:Codec -> string;
        abstract member bit_string_external_field_fixed_size : sTypeDefName:string -> p:string -> sErrCode:string -> sAcc:string -> noSizeMin:BigInteger option -> nSizeMax:BigInteger -> sExtFld:string -> codec:Codec -> string;
        abstract member bit_string_null_terminated : sTypeDefName:string -> p:string -> sErrCode:string -> sAcc:string -> i:string -> noSizeMin:BigInteger option -> nSizeMax:BigInteger -> arruNullBytes:seq<byte> -> nBitPatternLength:BigInteger -> codec:Codec -> string;
        abstract member RefTypeParam_tmpVar : sName:string -> sTypeDecl:string -> string;
        abstract member ReferenceType1 : p:string -> sName:string -> bAcnEncodeFuncRequiresResult:bool -> arrsArgs:seq<string> -> arrsLocalPrms:seq<string> -> codec:Codec -> string;
        abstract member sequence_presence_optChild : p:string -> sAcc:string -> sChName:string -> soExistVar:string option -> sErrCode:string -> codec:Codec -> string;
        abstract member sequence_presence_optChild_pres_acn_expression : p:string -> sAcc:string -> sChName:string -> sAcnExpression:string -> soExistVar:string option -> sErrCode:string -> codec:Codec -> string;
        abstract member sequence_presence_optChild_pres_bool : p:string -> sAcc:string -> sChName:string -> sExtFldName:string -> codec:Codec -> string;
        abstract member sequence_presence_optChild_pres_int : p:string -> sAcc:string -> sChName:string -> sExtFldName:string -> nIntVal:BigInteger -> codec:Codec -> string;
        abstract member sequence_presence_optChild_pres_str : p:string -> sAcc:string -> sChName:string -> sExtFldName:string -> sVal:string -> codec:Codec -> string;
        abstract member sequence_save_bitStream_start : sBitStreamPositionsLocalVar:string -> codec:Codec -> string;
        abstract member sequence_save_bitstream : sBitStreamPositionsLocalVar:string -> sChName:string -> codec:Codec -> string;
        abstract member sequence_acn_child : sChName:string -> sChildContent:string -> sErrCode:string -> soSaveBitStrmPosStatement:string option -> codec:Codec -> string;
        abstract member sequence_mandatory_child : sChName:string -> sChildContent:string -> soSaveBitStrmPosStatement:string option -> codec:Codec -> string;
        abstract member sequence_always_present_child : p:string -> sAcc:string -> sChName:string -> soChildContent:string option -> soChildExpr:string option -> sChildTypedef:string -> soSaveBitStrmPosStatement:string option -> codec:Codec -> string;
        abstract member sequence_always_absent_child : p:string -> sAcc:string -> sChName:string -> sChildContent:string -> sChildTypedef:string -> soSaveBitStrmPosStatement:string option -> codec:Codec -> string;
        abstract member sequence_optional_child : p:string -> sAcc:string -> sChName:string -> sChildContent:string -> soExistVar:string option -> soChildExpr:string option -> sChildTypedef:string -> soSaveBitStrmPosStatement:string option -> codec:Codec -> string;
        abstract member sequence_default_child : p:string -> sAcc:string -> sChName:string -> sChildContent:string -> sInitWithDefaultValue:string -> soExistVar:string option -> soChildExpr:string option -> sChildTypedef:string -> soSaveBitStrmPosStatement:string option -> codec:Codec -> string;
        abstract member sequence_call_post_encoding_function : p:string -> sFncName:string -> sBitStreamStartPos:string -> sBitStreamPositionsNullPos:string -> string;
        abstract member sequence_call_post_decoding_validator : p:string -> sFncName:string -> sBitStreamStartPos:string -> sBitStreamPositionsNullPos:string -> string;
        abstract member ChoiceChildAlwaysAbsent : p:string -> sAcc:string -> sChildID:string -> nChildIndex:BigInteger -> sErrorCodeName:string -> codec:Codec -> string;
        abstract member ChoiceChild : p:string -> sAcc:string -> sChildID:string -> nChildIndex:BigInteger -> nIndexSizeInBits:BigInteger -> nLastItemIndex:BigInteger -> sChildContent:string -> sChildName:string -> sChildTypeDef:string -> sChoiceTypeName:string -> sChildInitExpr:string -> codec:Codec -> string;
        abstract member Choice : p:string -> sAcc:string -> arrsChildren:seq<string> -> nLastItemIndex:BigInteger -> sChoiceIndexName:string -> td:FE_ChoiceTypeDefinition -> nIndexSizeInBits:BigInteger -> sErrCode:string -> codec:Codec -> string;
        abstract member ChoiceChild_preWhen : p:string -> sAcc:string -> sChildID:string -> sChildBody:string -> arrsConditions:seq<string> -> bFirst:bool -> sChildName:string -> sChildTypeDef:string -> sChoiceTypeName:string -> sChildInitExpr:string -> codec:Codec -> string;
        abstract member ChoiceChild_preWhen_bool_condition : sExtFld:string -> string;
        abstract member ChoiceChild_preWhen_int_condition : sExtFld:string -> sVal:string -> string;
        abstract member ChoiceChild_preWhen_str_condition : sExtFld:string -> sVal:string -> arrsNullChars:seq<string> -> arruVal:seq<byte> -> string;
        abstract member Choice_preWhen : p:string -> sAcc:string -> arrsChildren:seq<string> -> sErrCode:string -> codec:Codec -> string;
        abstract member ChoiceChild_Enum : p:string -> sAcc:string -> sEnmName:string -> sChildID:string -> sChildBody:string -> sChildName:string -> sChildTypeDef:string -> sChoiceTypeName:string -> sChildInitExpr:string -> codec:Codec -> string;
        abstract member Choice_Enum : p:string -> sAcc:string -> arrsChildren:seq<string> -> sEnmExtFld:string -> sErrCode:string -> codec:Codec -> string;
        abstract member SizeDependency : v:string -> sCount:string -> nMin:BigInteger -> nMax:BigInteger -> bCheckRange:bool -> sTypedefName:string -> string;
        abstract member SizeDependencyFixedSize : v:string -> nFixedSize:BigInteger -> string;
        abstract member ChoiceDependencyEnum_Item : v:string -> sChildCID:string -> sChildCIDHolder:string -> sEnumCName:string -> bIsOptional:bool -> string;
        abstract member ChoiceDependencyEnum : sV:string -> sChPath:string -> sAcc:string -> arrsChoiceEnumItems:seq<string> -> bIsOptional:bool -> sDefaultExpr:string -> string;
        abstract member PresenceDependency : v:string -> sSeqPath:string -> sAcc:string -> sChildName:string -> string;
        abstract member ChoiceDependencyIntPres_child : v:string -> sChildNamePresent:string -> sChildRetVal:string -> string;
        abstract member ChoiceDependencyStrPres_child : v:string -> sChildNamePresent:string -> sChildRetVal:string -> arruChildRetValBytes:seq<byte> -> arrsNullChars:seq<string> -> string;
        abstract member ChoiceDependencyPres : v:string -> sChPath:string -> sAcc:string -> arrsChoiceItems:seq<string> -> string;
        abstract member MultiAcnUpdate_checkEqual_pri0 : p1:string -> p2:string -> string;
        abstract member MultiAcnUpdate_checkEqual_str0 : p1:string -> p2:string -> string;
        abstract member MultiAcnUpdate_get_first_init_value_pri : sV0:string -> sVi:string -> sChPath:string -> bIsFirst:bool -> bIsSingleElement:bool -> string;
        abstract member MultiAcnUpdate_get_first_init_value_str : sV0:string -> sVi:string -> sChPath:string -> bIsFirst:bool -> bIsSingleElement:bool -> string;
        abstract member MultiAcnUpdate_checkEqual_pri : sV0:string -> sVi:string -> sChPath:string -> bIsAlwaysInit:bool -> string;
        abstract member MultiAcnUpdate_checkEqual_str : sV0:string -> sVi:string -> sChPath:string -> bIsAlwaysInit:bool -> string;
        abstract member MultiAcnUpdate : v:string -> sV0:string -> sErrCode:string -> arrsLocalDeclarations:seq<string> -> arrsLocalUpdateStatements:seq<string> -> arrsGetFirstIntValue:seq<string> -> bIsFirstIntValueSingle:bool -> arrsLocalCheckEquality:seq<string> -> sDefaultExpr:string -> string;
        abstract member checkAccessPath : arrsCheckPaths:seq<string> -> sUpdateStatement:string -> v:string -> sInitExpr:string -> string;
        abstract member SizeDependency_oct_str_containing : p:string -> sFuncName:string -> sReqBytesForUperEncoding:string -> v:string -> bIsOctet:bool -> sComment:string -> string;
        abstract member octet_string_containing_ext_field_func : p:string -> sFuncName:string -> sReqBytesForUperEncoding:string -> sExtField:string -> sErrCode:string -> soInner:string option -> codec:Codec -> string;
        abstract member bit_string_containing_ext_field_func : p:string -> sFuncName:string -> sReqBytesForUperEncoding:string -> sReqBitsForUperEncoding:string -> sExtField:string -> sErrCode:string -> codec:Codec -> string;
        abstract member rtlModuleName : unit -> string;
        abstract member sparkAnnotations : sTypeDefName:string -> codec:Codec -> string;
        abstract member octet_string_containing_func : p:string -> sFuncName:string -> sReqBytesForAcnEncoding:string -> nBits:BigInteger -> nMinSize:BigInteger -> nMaxSize:BigInteger -> bFixedSize:bool -> codec:Codec -> string;
        abstract member bit_string_containing_func : p:string -> sFuncName:string -> sReqBytesForAcnEncoding:string -> sReqBitsForUperEncoding:string -> nBits:BigInteger -> nMinSize:BigInteger -> nMaxSize:BigInteger -> bFixedSize:bool -> codec:Codec -> string;


    [<AbstractClass>]
    type IXer () =
        abstract member rtlModuleName : unit -> string;
        abstract member EmitTypeAssignment_def_err_code : sErrCode:string -> nErrValue:BigInteger -> string;
        abstract member EmitTypeAssignment_def : sVarName:string -> sStar:string -> sFuncName:string -> sTypeDefName:string -> arrsErrcodes:seq<string> -> bEmptyEncodingSpace:bool -> nMaxBytesInXER:BigInteger -> soSparkAnnotations:string option -> codec:Codec -> string;
        abstract member EmitTypeAssignment : sTasName:string -> sVarName:string -> sStar:string -> sFuncName:string -> soIValidFuncName:string option -> sTypeDefName:string -> arrsLocalVariables:seq<string> -> sContent:string -> soSparkAnnotations:string option -> sInitialExp:string -> codec:Codec -> string;
        abstract member Integer : p:string -> sTag:string -> nLevel:BigInteger -> soCheckExp:string option -> sErrCode:string -> codec:Codec -> string;
        abstract member IntegerPos : p:string -> sTag:string -> nLevel:BigInteger -> soCheckExp:string option -> sErrCode:string -> codec:Codec -> string;
        abstract member Boolean : p:string -> sTag:string -> nLevel:BigInteger -> soCheckExp:string option -> sErrCode:string -> codec:Codec -> string;
        abstract member Real : p:string -> sTag:string -> nLevel:BigInteger -> soCheckExp:string option -> sErrCode:string -> codec:Codec -> string;
        abstract member ObjectIdentifier : p:string -> sTag:string -> nLevel:BigInteger -> soCheckExp:string option -> sErrCode:string -> codec:Codec -> string;
        abstract member TimeType : p:string -> sTimeSubType:string -> sTag:string -> nLevel:BigInteger -> soCheckExp:string option -> sErrCode:string -> codec:Codec -> string;
        abstract member Null : p:string -> sTag:string -> nLevel:BigInteger -> soCheckExp:string option -> sErrCode:string -> codec:Codec -> string;
        abstract member String : p:string -> sTag:string -> nLevel:BigInteger -> soCheckExp:string option -> sErrCode:string -> codec:Codec -> string;
        abstract member Enumerated_item : p:string -> sTag:string -> nLevel:BigInteger -> sItemID:string -> sXerValue:string -> sErrCode:string -> bFirst:bool -> codec:Codec -> string;
        abstract member Enumerated : p:string -> sTag:string -> nLevel:BigInteger -> arrsItems:seq<string> -> soCheckExp:string option -> sErrCode:string -> codec:Codec -> string;
        abstract member OctetString : p:string -> sAcc:string -> sTag:string -> nLevel:BigInteger -> nSizeMax:BigInteger -> bIsFixedSize:bool -> soCheckExp:string option -> sErrCode:string -> codec:Codec -> string;
        abstract member BitString : p:string -> sAcc:string -> sTag:string -> nLevel:BigInteger -> nSizeMax:BigInteger -> bIsFixedSize:bool -> soCheckExp:string option -> sErrCode:string -> codec:Codec -> string;
        abstract member SequenceOf : p:string -> sAcc:string -> sTag:string -> nLevel:BigInteger -> sI:string -> nSizeMax:BigInteger -> sChildBody:string -> bFixedSize:bool -> soCheckExp:string option -> sErrCode:string -> codec:Codec -> string;
        abstract member Sequence_mandatory_child : sChName:string -> sChildContent:string -> sChildTag:string -> codec:Codec -> string;
        abstract member Sequence_optional_child : p:string -> sAcc:string -> sChName:string -> sChildContent:string -> sChildTag:string -> codec:Codec -> string;
        abstract member Sequence_default_child : p:string -> sAcc:string -> sChName:string -> sChildContent:string -> sChildTag:string -> sInitWithDefaultValue:string -> codec:Codec -> string;
        abstract member SEQUENCE_start : p:string -> sTag:string -> nLevel:BigInteger -> sErrCode:string -> bEmptySequence:bool -> codec:Codec -> string;
        abstract member SEQUENCE_end : sTag:string -> nLevel:BigInteger -> sErrCode:string -> codec:Codec -> string;
        abstract member SEQUENCE_xer : sChildren:string -> codec:Codec -> string;
        abstract member CHOICE_child : p:string -> sAcc:string -> sChID:string -> sChildBody:string -> bFirst:bool -> sChildTag:string -> sChildName:string -> sChildTypeDef:string -> sChoiceTypeName:string -> codec:Codec -> string;
        abstract member CHOICE_no_tag : p:string -> sAcc:string -> arrsChildren:seq<string> -> sErrCode:string -> codec:Codec -> string;
        abstract member CHOICE : p:string -> sAcc:string -> sTag:string -> nLevel:BigInteger -> sMainBody:string -> sErrCode:string -> codec:Codec -> string;
        abstract member call_base_type_func : p:string -> sXmlTag:string -> sFuncName:string -> codec:Codec -> string;


    [<AbstractClass>]
    type ITestCases () =
        abstract member rtlModuleName : unit -> string;
        abstract member PrintAutomaticTestCasesSpecFile : sModNameUpperCase:string -> sModName:string -> arrsIncludedModules:seq<string> -> arrsTestFunctions:seq<string> -> string;
        abstract member PrintAutomaticTestCasesBodyFile : sModName:string -> sTetscaseSpecFileName:string -> arrsIncludedModules:seq<string> -> arrsTasNames:seq<string> -> arrsTypeAssignments:seq<string> -> bXer:bool -> string;
        abstract member Codec_Encode : sModName:string -> sFuncName:string -> sVal:string -> string;
        abstract member Codec_Decode : sModName:string -> sFuncName:string -> sTasName:string -> sEnc:string -> sAmber:string -> string;
        abstract member Codec_Decode_XER : sModName:string -> sFuncName:string -> sTasName:string -> sEnc:string -> sAmber:string -> string;
        abstract member Codec_validate_output : sModName:string -> sFuncName:string -> sAmber:string -> string;
        abstract member Codec_compare_input_with_output : sModName:string -> sFuncName:string -> sVal:string -> sAmber:string -> string;
        abstract member Codec_write_CharstreamToFile : unit -> string;
        abstract member Codec_write_bitstreamToFile : unit -> string;
        abstract member JoinItems : sPart:string -> soNestedPart:string option -> string;
        abstract member Codec_declare_EncInDecOut_variable : sPrmName:string -> sType:string -> sPrmValue:string -> string;
        abstract member Codec_declare_DecIn_variable : sPrmName:string -> sType:string -> string;
        abstract member PrintCodec_spec : sFuncName:string -> sModName:string -> sTasName:string -> sStar:string -> sVal:string -> string;
        abstract member PrintCodec_body : sModName:string -> sFuncName:string -> sTasName:string -> sStar:string -> sVal:string -> sEnc:string -> sNestedStatements:string -> sCodecClass:string -> string;
        abstract member PrintCodec_body_XER : sModName:string -> sFuncName:string -> sTasName:string -> sStar:string -> sVal:string -> sEnc:string -> sNestedStatements:string -> string;
        abstract member PrintMain : sTestSuiteFilename:string -> string;
        abstract member PrintSuite_call_codec_generate_dat_file : sModName:string -> sTasName:string -> sAmber:string -> sEnc:string -> sStreamName:string -> string;
        abstract member PrintATCRunnerDefinition : unit -> string;
        abstract member PrintATCRunner : sTestSuiteFilename:string -> arrsIncludedModules:seq<string> -> arrsVars:seq<string> -> arrsTestFunctions:seq<string> -> arrsUsedPackages:seq<string> -> arrsInitCalls:seq<string> -> bGenerateDatFile:bool -> string;
        abstract member invokeTestCaseAsFunc : sFuncName:string -> string;
        abstract member emitTestCaseAsFunc_h : sFuncName:string -> string;
        abstract member emitTestCaseAsFunc_dummy_init : sTypeName:string -> sFuncName:string -> sDummyVarname:string -> string;
        abstract member emitTestCaseAsFunc_dummy_init_function : sTypeName:string -> sFuncName:string -> sDummyVarname:string -> string;
        abstract member emitTestCaseAsFunc : sFuncName:string -> arrsVars:seq<string> -> sModName:string -> sTasName:string -> sAmber:string -> sEnc:string -> bValueAssignment:bool -> sInitializeTcData:string -> bStatic:bool -> sGenerateDatFile:string -> arrsDummyInitStatementsNeededForStatementCoverage:seq<string> -> sInitAmber:string -> string;
        abstract member printTestCaseFileDef : sThisFile:string -> arrsIncludedModules:seq<string> -> arrsTestFunctionDefs:seq<string> -> string;
        abstract member printTestCaseFileBody : sThisFile:string -> arrsIncludedModules:seq<string> -> arrsTestFunctionBodies:seq<string> -> string;


    [<AbstractClass>]
    type IAux () =
        abstract member PrintMakeFile : arrsFilesNoExt:seq<string> -> bWordSize4:bool -> bFpWordSize4:bool -> bAsn1sccStreaming:bool -> string;
        abstract member emitVisualStudioSolution : unit -> string;

