-- Code automatically generated by asn1scc tool
WITH adaasn1rtl;
USE adaasn1rtl;
use type adaasn1rtl.OctetBuffer;
use type adaasn1rtl.BitArray;
use type adaasn1rtl.Asn1UInt;
use type adaasn1rtl.Asn1Int;
use type adaasn1rtl.BIT;
--# inherit adaasn1rtl;


PACKAGE mapFunctions
IS

   FUNCTION milbus2_encode(IntVal:IN Asn1Int) RETURN Asn1Int;
   FUNCTION milbus2_decode(IntVal:IN Asn1Int) RETURN Asn1Int;


END mapFunctions;
