-- Code automatically generated by asn1scc tool
WITH adaasn1rtl;
use type adaasn1rtl.Asn1UInt;
use type adaasn1rtl.Asn1Int;
use type adaasn1rtl.BIT;


PACKAGE BODY mapFunctions IS


   FUNCTION milbus2_encode(IntVal:IN Asn1Int) RETURN Asn1Int
   is
      ret : Asn1Int;
   begin
      if IntVal = 32 then
         ret := 0;
      else
         ret := IntVal;
      end if;
      return ret;
   end milbus2_encode;

   FUNCTION milbus2_decode(IntVal:IN Asn1Int) RETURN Asn1Int
   is
      ret : Asn1Int;
   begin
      if IntVal = 0 then
         ret := 32;
      else
         ret := IntVal;
      end if;
      return ret;
   end milbus2_decode;



END mapFunctions;
