#ifndef _INC_B_AUTO_TCS_H_H
#define _INC_B_AUTO_TCS_H_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "b.h"

#ifdef  __cplusplus
extern "C" {
#endif


flag RGBCOLORS_enc_dec(const RGBCOLORS* pVal, int* pErrCode);

flag OTHERCOLORS_enc_dec(const OTHERCOLORS* pVal, int* pErrCode);

flag CH2_left_enc_dec(const CH2_left* pVal, int* pErrCode);

flag CH2_enc_dec(const CH2* pVal, int* pErrCode);

flag CH1_left_enc_dec(const CH1_left* pVal, int* pErrCode);

flag CH1_enc_dec(const CH1* pVal, int* pErrCode);



#ifdef  __cplusplus
}
#endif

#endif
