/*
Code automatically generated by asn1scc tool
*/
package asn1src

import asn1scala._
import stainless.lang._
import stainless.annotation._

type ApplicationProcess_ID = UInt // header_scala:83


@inline @cCode.inline val ERR_APPLICATIONPROCESS_ID: Int = 51  /*(0 .. 2047) isvalid_scala:68 */

 

@inline @cCode.inline val ERR_UPER_ENCODE_APPLICATIONPROCESS_ID: Int = 52  /**/
@inline @cCode.inline val ApplicationProcess_ID_REQUIRED_BYTES_FOR_ENCODING: Int = 2 
@inline @cCode.inline val ApplicationProcess_ID_REQUIRED_BITS_FOR_ENCODING: Int = 11

 

 