/*
Code automatically generated by asn1scc tool
*/
package asn1src

import asn1scala._
import stainless.lang._
import stainless.annotation._

type DummyType = UInt // header_scala:83


@inline @cCode.inline val ERR_DUMMYTYPE: Int = 46  /*(15) isvalid_scala:68 */

 

@inline @cCode.inline val ERR_UPER_ENCODE_DUMMYTYPE: Int = 47  /**/
@inline @cCode.inline val DummyType_REQUIRED_BYTES_FOR_ENCODING: Int = 0 
@inline @cCode.inline val DummyType_REQUIRED_BITS_FOR_ENCODING: Int = 0

 

 