/*
Code automatically generated by asn1scc tool
*/

#include <string.h>
#include <math.h>
#include <limits.h>
#include "asn1crt.h"
#include "a_auto_tcs.h"


flag OOO_enc_dec(const OOO* pVal, int* pErrCode)
{
    static OOO decodedPDU;
    static byte encBuff[OOO_REQUIRED_BYTES_FOR_ENCODING + 1]; /* +1 for zerosized types */
    BitStream bitStrm;
    flag ret = TRUE;

    BitStream_Init(&bitStrm, encBuff, OOO_REQUIRED_BYTES_FOR_ENCODING);
    // Encode value
    ret = OOO_Encode(pVal, &bitStrm, pErrCode, TRUE);
    *pErrCode = ret ? 0 : 1;
    if (ret) {
        BitStream_AttachBuffer(&bitStrm, encBuff, OOO_REQUIRED_BYTES_FOR_ENCODING);
        // Decode value
        ret = OOO_Decode(&decodedPDU, &bitStrm, pErrCode);
        *pErrCode = ret ? 0 : 2;
        if (ret) {
            if (ret) {
                ret = OOO_Equal(pVal, &decodedPDU);
                *pErrCode = ret ? 0 : 4;
            
            }
        
        }
    
    }

    return ret;
}
