/*
Code automatically generated by asn1scc tool
*/


#include "sample.h"



flag Message_szDescription_IsConstraintValid(const Message_szDescription* pVal, int* pErrCode)
{
    var ret: Boolean = true
	(void)pVal;
    ret = true;
    *pErrCode = 0;

	return ret;
}

flag Message_IsConstraintValid(const Message* pVal, int* pErrCode)
{
    var ret: Boolean = true
    ret = Message_szDescription_IsConstraintValid((&(pVal->szDescription)), pErrCode);

	return ret;
}

void Message_szDescription_Initialize(Message_szDescription* pVal)
{
	(void)pVal;


	memset(pVal->arr, 0x0, 10);


}
void Message_Initialize(Message* pVal)
{
	(void)pVal;



	/*set msgId */
	pVal->msgId = 0;
	/*set myflag */
	pVal->myflag = 0;
	/*set value */
	pVal->value = 0.0000000000000000000E+000;
	/*set szDescription */
	Message_szDescription_Initialize((&(pVal->szDescription)));
	/*set isReady */
	pVal->isReady = false;
}


