-- Code automatically generated by asn1scc tool
with adaasn1rtl;
with system;
use adaasn1rtl;
WITH adaasn1rtl.encoding;
WITH adaasn1rtl.encoding.acn;
WITH MYMODULE;

use type adaasn1rtl.OctetBuffer;
use type adaasn1rtl.BitArray;
use type adaasn1rtl.Asn1UInt;
use type adaasn1rtl.Asn1Int;
use type adaasn1rtl.BIT;
use MYMODULE;
--# inherit ;


PACKAGE postencoding with SPARK_Mode
IS

procedure my_encoding_patcher(val:in Packet; bitStreamPositions_start1 : adaasn1rtl.encoding.BitStreamPtr; bitStreamPositions_1:Packet_extension_function_positions; bs : in out adaasn1rtl.encoding.Bitstream);

FUNCTION crc_validator(val:in Packet; bitStreamPositions_start1 : adaasn1rtl.encoding.BitStreamPtr; bitStreamPositions_1:Packet_extension_function_positions; bs : in out adaasn1rtl.encoding.Bitstream) return adaasn1rtl.ASN1_RESULT;


END postencoding;
