-- Code automatically generated by asn1scc tool
WITH adaasn1rtl;
WITH MOD1;
--# inherit adaasn1rtl,MOD1;
PACKAGE MOD1_auto_encs_decs
IS

FUNCTION RGBCOLORS_uPER_enc_dec(val:MOD1.RGBCOLORS) RETURN adaasn1rtl.TEST_CASE_RESULT;

FUNCTION CH1_uPER_enc_dec(val:MOD1.CH1) RETURN adaasn1rtl.TEST_CASE_RESULT;

FUNCTION CH1_left_uPER_enc_dec(val:MOD1.CH1_left) RETURN adaasn1rtl.TEST_CASE_RESULT;

END MOD1_auto_encs_decs;