#ifndef _INC_A_AUTO_TCS_H_H
#define _INC_A_AUTO_TCS_H_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "a.h"

#ifdef  __cplusplus
extern "C" {
#endif


flag RGBCOLORS_enc_dec(const RGBCOLORS* pVal, int* pErrCode);

flag CH1_left_enc_dec(const CH1_left* pVal, int* pErrCode);

flag CH1_enc_dec(const CH1* pVal, int* pErrCode);



#ifdef  __cplusplus
}
#endif

#endif
