/*
Code automatically generated by asn1scc tool
*/

import stainless.lang._


type DummyType = UInt // header_scala:83


@inline @cCode.inline val ERR_DUMMYTYPE: Int = 36  /*(15) isvalid_scala:68 */

 

@inline @cCode.inline val ERR_UPER_ENCODE_DUMMYTYPE: Int = 37  /**/
@inline @cCode.inline val DummyType_REQUIRED_BYTES_FOR_ENCODING: Int = 0 
@inline @cCode.inline val DummyType_REQUIRED_BITS_FOR_ENCODING: Int = 0

 

 