/*
Code automatically generated by asn1scc tool
*/

val eventDefinition_ID_Size: Int = 32 // variables_scala:188 // body_scala:10, move to definition if needed somewhere else

def EventDefinitionAuxiliaryData_IsConstraintValid(intRef: Ref[EventDefinitionAuxiliaryData]): Int = 
{
    var ret = 0 // isvalid_scala.stg:80

    ret = DummyType_IsConstraintValid((intRef))

    ret
}

def EventDefinitionAuxiliaryData_Initialize(pVal: Ref[EventDefinitionAuxiliaryData]): Unit = // init_scala:12
{
	(pVal).x = 15;
}

def EventDefinitionAuxiliaryData_Encode(intRef: Ref[EventDefinitionAuxiliaryData], pBitStrm: Ref[BitStream], bCheckConstraints: Boolean): Int = //uper_scala:23
{
    var ret = 0

    if (bCheckConstraints) 
        ret = EventDefinitionAuxiliaryData_IsConstraintValid(intRef)
    if (ret == 0) {
        ret = DummyType_Encode((intRef), pBitStrm, pErrCode, FALSE);
    }
    
    ret
}

def EventDefinitionAuxiliaryData_Decode(pVal: EventDefinitionAuxiliaryData, pBitStrm: Ref[BitStream]): Int = 
{
    var ret = 0;


    ret = DummyType_Decode((pVal), pBitStrm, pErrCode);

    if (ret == 0)
        ret = EventDefinitionAuxiliaryData_IsConstraintValid(pVal) 
    ret
} // body_scala:10, move to definition if needed somewhere else

def EventDefinition_ID_IsConstraintValid(intRef: Ref[EventDefinition_ID]): Int = 
{
    var ret = 0 // isvalid_scala.stg:80

    if (((intRef).x <= 4294967295)) 0 else ERR_EVENTDEFINITION_ID // isvalid_scala:51

    ret
}

def EventDefinition_ID_Initialize(pVal: Ref[EventDefinition_ID]): Unit = // init_scala:12
{
	(pVal).x = 0;
}

def EventDefinition_ID_Encode(intRef: Ref[EventDefinition_ID], pBitStrm: Ref[BitStream], bCheckConstraints: Boolean): Int = //uper_scala:23
{
    var ret = 0

    if (bCheckConstraints) 
        ret = EventDefinition_ID_IsConstraintValid(intRef)
    if (ret == 0) {
        BitStream_EncodeConstraintPosWholeNumber(pBitStrm, (intRef).x, 0, 4294967295);
    }
    
    ret
}

def EventDefinition_ID_Decode(pVal: EventDefinition_ID, pBitStrm: Ref[BitStream]): Int = 
{
    var ret = 0;


    if(!BitStream_DecodeConstraintPosWholeNumber(pBitStrm, (pVal), 0, 4294967295))
        ret = ERR_UPER_DECODE_EVENTDEFINITION_ID // uper_scala:153

    if (ret == 0)
        ret = EventDefinition_ID_IsConstraintValid(pVal) 
    ret
} // body_scala:10, move to definition if needed somewhere else