package EventDefinition // header_scala:10

/*
Code automatically generated by asn1scc tool
*/

import stainless.lang._

type EventDefinitionAuxiliaryData = DummyType // header_scala:83


@inline @cCode.inline val ERR_EVENTDEFINITIONAUXILIARYDATA_2: Int = 46  /* isvalid_scala:68 */

 

@inline @cCode.inline val ERR_UPER_ENCODE_EVENTDEFINITIONAUXILIARYDATA_2: Int = 47  /**/
@inline @cCode.inline val EventDefinitionAuxiliaryData_REQUIRED_BYTES_FOR_ENCODING: Int = 0 
@inline @cCode.inline val EventDefinitionAuxiliaryData_REQUIRED_BITS_FOR_ENCODING: Int = 0

 
type EventDefinition_ID = UInt // header_scala:83


@inline @cCode.inline val ERR_EVENTDEFINITION_ID: Int = 36  /*(0 .. 4294967295) isvalid_scala:68 */

 

@inline @cCode.inline val ERR_UPER_ENCODE_EVENTDEFINITION_ID: Int = 37  /**/
@inline @cCode.inline val EventDefinition_ID_REQUIRED_BYTES_FOR_ENCODING: Int = 4 
@inline @cCode.inline val EventDefinition_ID_REQUIRED_BITS_FOR_ENCODING: Int = 32

 

val eventDefinition_ID_Size: Int = 32 