/*
Code automatically generated by asn1scc tool
*/

import stainless.lang._

import Dummy
import ApplicationProcess

type EventDefinitionAuxiliaryData = DummyType // header_scala:83


@inline @cCode.inline val ERR_EVENTDEFINITIONAUXILIARYDATA_2: Int = 51  /* isvalid_scala:68 */

 

@inline @cCode.inline val ERR_UPER_ENCODE_EVENTDEFINITIONAUXILIARYDATA_2: Int = 52  /**/
@inline @cCode.inline val EventDefinitionAuxiliaryData_REQUIRED_BYTES_FOR_ENCODING: Int = 0 
@inline @cCode.inline val EventDefinitionAuxiliaryData_REQUIRED_BITS_FOR_ENCODING: Int = 0

 
type EventDefinition_ID = UInt // header_scala:83


@inline @cCode.inline val ERR_EVENTDEFINITION_ID: Int = 41  /*(0 .. 4294967295) isvalid_scala:68 */

 

@inline @cCode.inline val ERR_UPER_ENCODE_EVENTDEFINITION_ID: Int = 42  /**/
@inline @cCode.inline val EventDefinition_ID_REQUIRED_BYTES_FOR_ENCODING: Int = 4 
@inline @cCode.inline val EventDefinition_ID_REQUIRED_BITS_FOR_ENCODING: Int = 32

 

extern const Int eventDefinition_ID_Size; 