/*
Code automatically generated by asn1scc tool
*/

import stainless.lang._
import stainless.annotation._

/*-- TM_5_1_InformativeEventReport --------------------------------------------*/
case class TM_5_1_InformativeEventReport (
    eventDefinition_ID: EventDefinition_ID,
    auxiliaryData: DummyType
)

@inline @cCode.inline val ERR_TM_5_1_INFORMATIVEEVENTREPORT: Int = 26  /* isvalid_scala:68 */
@inline @cCode.inline val ERR_TM_5_1_INFORMATIVEEVENTREPORT_EVENTDEFINITION_ID_2: Int = 6  /* isvalid_scala:68 */
@inline @cCode.inline val ERR_TM_5_1_INFORMATIVEEVENTREPORT_AUXILIARYDATA_2_2: Int = 21  /* isvalid_scala:68 */

 

@inline @cCode.inline val ERR_UPER_ENCODE_TM_5_1_INFORMATIVEEVENTREPORT: Int = 27  /**/
@inline @cCode.inline val ERR_UPER_ENCODE_TM_5_1_INFORMATIVEEVENTREPORT_EVENTDEFINITION_ID_2: Int = 7  /**/
@inline @cCode.inline val ERR_UPER_ENCODE_TM_5_1_INFORMATIVEEVENTREPORT_AUXILIARYDATA_2_2: Int = 22  /**/
@inline @cCode.inline val TM_5_1_InformativeEventReport_REQUIRED_BYTES_FOR_ENCODING: Int = 4 
@inline @cCode.inline val TM_5_1_InformativeEventReport_REQUIRED_BITS_FOR_ENCODING: Int = 32

 

 