// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Asn1f2 {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Asn1f2.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string gnat {
            get {
                return ResourceManager.GetString("gnat", resourceCulture);
            }
        }
        
        internal static string IgnoredExaminerWarnings {
            get {
                return ResourceManager.GetString("IgnoredExaminerWarnings", resourceCulture);
            }
        }
        
        internal static string GPS_project {
            get {
                return ResourceManager.GetString("GPS_project", resourceCulture);
            }
        }
        
        internal static string run {
            get {
                return ResourceManager.GetString("run", resourceCulture);
            }
        }
        
        internal static string asn1crt_acn_h {
            get {
                return ResourceManager.GetString("asn1crt_acn_h", resourceCulture);
            }
        }
        
        internal static string asn1crt_ber_h {
            get {
                return ResourceManager.GetString("asn1crt_ber_h", resourceCulture);
            }
        }
        
        internal static string asn1crt_core_h {
            get {
                return ResourceManager.GetString("asn1crt_core_h", resourceCulture);
            }
        }
        
        internal static string asn1crt_real_h {
            get {
                return ResourceManager.GetString("asn1crt_real_h", resourceCulture);
            }
        }
        
        internal static string asn1crt_util_h {
            get {
                return ResourceManager.GetString("asn1crt_util_h", resourceCulture);
            }
        }
        
        internal static string asn1crt_xer_h {
            get {
                return ResourceManager.GetString("asn1crt_xer_h", resourceCulture);
            }
        }
        
        internal static string asn1crt_h {
            get {
                return ResourceManager.GetString("asn1crt_h", resourceCulture);
            }
        }
        
        internal static string BitStream_h {
            get {
                return ResourceManager.GetString("BitStream_h", resourceCulture);
            }
        }
        
        internal static string ByteStream_h {
            get {
                return ResourceManager.GetString("ByteStream_h", resourceCulture);
            }
        }
        
        internal static string Acn_c {
            get {
                return ResourceManager.GetString("Acn_c", resourceCulture);
            }
        }
        
        internal static string ber_c {
            get {
                return ResourceManager.GetString("ber_c", resourceCulture);
            }
        }
        
        internal static string BitStream_c {
            get {
                return ResourceManager.GetString("BitStream_c", resourceCulture);
            }
        }
        
        internal static string ByteStream_c {
            get {
                return ResourceManager.GetString("ByteStream_c", resourceCulture);
            }
        }
        
        internal static string real_c {
            get {
                return ResourceManager.GetString("real_c", resourceCulture);
            }
        }
        
        internal static string util_c {
            get {
                return ResourceManager.GetString("util_c", resourceCulture);
            }
        }
        
        internal static string xer_c {
            get {
                return ResourceManager.GetString("xer_c", resourceCulture);
            }
        }
        
        internal static string adaasn1rtl_adb {
            get {
                return ResourceManager.GetString("adaasn1rtl_adb", resourceCulture);
            }
        }
        
        internal static string adaasn1rtl_ads {
            get {
                return ResourceManager.GetString("adaasn1rtl_ads", resourceCulture);
            }
        }
    }
}
